--swallow-optional-blank-lines
--no-blank-lines-after-declarations
--blank-lines-after-procedures
--braces-on-if-line
--cuddle-else
--no-space-after-casts
--no-space-after-function-call-names
--no-tabs
--indent-level 4
--comment-indentation 25
-T PyObject
-T PyCFunction
