self-hosted-runner:
  # Pending release of actionlint > 1.7.11 for macos-26-intel support
  # https://github.com/rhysd/actionlint/pull/629
  labels: ["macos-26-intel"]

config-variables: null

paths:
  .github/workflows/**/*.yml:
     ignore:
     - 1st argument of function call is not assignable
     - SC2(015|038|086|091|097|098|129|155)
