self-hosted-runner:
  # Pending https://github.com/rhysd/actionlint/pull/615
  labels: ["windows-2025-vs2026"]

config-variables: null

paths:
  .github/workflows/**/*.yml:
     ignore:
     - 1st argument of function call is not assignable
     - SC2(015|038|086|091|097|098|129|155)
