		pcbuild\amd64\python.exe Tools\scripts\deepfreeze.py Lib/importlib\_bootstrap.py -m importlib._bootstrap -o Python\deepfreeze\importlib._bootstrap.c
		pcbuild\amd64\python.exe Tools\scripts\deepfreeze.py Lib/importlib\_bootstrap_external.py -m importlib._bootstrap_external -o Python\deepfreeze\importlib._bootstrap_external.c
		pcbuild\amd64\python.exe Tools\scripts\deepfreeze.py Lib/zipimport.py -m zipimport -o Python\deepfreeze\zipimport.c
		pcbuild\amd64\python.exe Tools\scripts\deepfreeze.py Lib/abc.py -m abc -o Python\deepfreeze\abc.c
		pcbuild\amd64\python.exe Tools\scripts\deepfreeze.py Lib/codecs.py -m codecs -o Python\deepfreeze\codecs.c
		pcbuild\amd64\python.exe Tools\scripts\deepfreeze.py Lib/io.py -m io -o Python\deepfreeze\io.c
		pcbuild\amd64\python.exe Tools\scripts\deepfreeze.py Lib/_collections_abc.py -m _collections_abc -o Python\deepfreeze\_collections_abc.c
		pcbuild\amd64\python.exe Tools\scripts\deepfreeze.py Lib/_sitebuiltins.py -m _sitebuiltins -o Python\deepfreeze\_sitebuiltins.c
		pcbuild\amd64\python.exe Tools\scripts\deepfreeze.py Lib/genericpath.py -m genericpath -o Python\deepfreeze\genericpath.c
		pcbuild\amd64\python.exe Tools\scripts\deepfreeze.py Lib/ntpath.py -m ntpath -o Python\deepfreeze\ntpath.c
		pcbuild\amd64\python.exe Tools\scripts\deepfreeze.py Lib/posixpath.py -m posixpath -o Python\deepfreeze\posixpath.c
		pcbuild\amd64\python.exe Tools\scripts\deepfreeze.py Lib/os.py -m os -o Python\deepfreeze\os.c
		pcbuild\amd64\python.exe Tools\scripts\deepfreeze.py Lib/site.py -m site -o Python\deepfreeze\site.c
		pcbuild\amd64\python.exe Tools\scripts\deepfreeze.py Lib/stat.py -m stat -o Python\deepfreeze\stat.c
		pcbuild\amd64\python.exe Tools\scripts\deepfreeze.py Lib/__hello__.py -m __hello__ -o Python\deepfreeze\__hello__.c
		pcbuild\amd64\python.exe Tools\scripts\deepfreeze.py Lib/__phello__\__init__.py -m __phello__ -o Python\deepfreeze\__phello__.c
		pcbuild\amd64\python.exe Tools\scripts\deepfreeze.py Lib/__phello__\ham\__init__.py -m __phello__.ham -o Python\deepfreeze\__phello__.ham.c
		pcbuild\amd64\python.exe Tools\scripts\deepfreeze.py Lib/__phello__\ham\eggs.py -m __phello__.ham.eggs -o Python\deepfreeze\__phello__.ham.eggs.c
		pcbuild\amd64\python.exe Tools\scripts\deepfreeze.py Lib/__phello__\spam.py -m __phello__.spam -o Python\deepfreeze\__phello__.spam.c
		pcbuild\amd64\python.exe Tools\scripts\deepfreeze.py Tools/freeze/flag.py -m frozen_only -o Python\deepfreeze\frozen_only.c