parser.dvi:  parser.tex ../../Doc/libparser.tex
	TEXINPUTS=../../Doc:: $(LATEX) parser

#  Use a new name for this; the included file uses 'clean' already....
clean-parser:
	rm -f *.log *.aux *.dvi *.pyc

include ../../Doc/Makefile
