# Current docs for the syntax of this file are at:
#  https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted.md

name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

queue:
  name: Hosted VS2017
  parallel: 2
  matrix:
    amd64:
      buildOpt: -p x64
      outDirSuffix: amd64
    win32:
      buildOpt:
      outDirSuffix: win32

trigger:
  branches:
    include:
    - master
    - 3.7
    - 3.6
  paths:
    exclude:
    - Doc/*
    - Tools/*

variables:
  # Relocate build outputs outside of source directory to make cleaning faster
  Py_IntDir: $(Build.BinariesDirectory)\obj
  # UNDONE: Do not build to a different directory because of broken tests
  Py_OutDir: $(Build.SourcesDirectory)\PCbuild
  EXTERNAL_DIR: $(Build.BinariesDirectory)\externals

steps:
- checkout: self
  clean: true
  fetchDepth: 5

- script: PCbuild\build.bat -e $(buildOpt)
  displayName: 'Build CPython'

- script: python.bat -m test.pythoninfo
  displayName: 'Display build info'

- script: PCbuild\rt.bat -q -uall -u-cpu -rwW --slowest --timeout=1200 -j0 --junit-xml="$(Build.BinariesDirectory)\test-results.xml"
  displayName: 'Tests'
  env:
    PREFIX: $(Py_OutDir)\$(outDirSuffix)

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFiles: '$(Build.BinariesDirectory)\test-results.xml'
    mergeTestResults: true
    testRunTitle: '$(Build.SourceBranchName)-$(outDirSuffix)'
    platform: $(outDirSuffix)
  condition: succeededOrFailed()
