context:
  # Keep up to date
  version: "3.15"

package:
  name: python
  version: ${{ version }}

source:
  - path: ../../..

build:
  files:
    exclude:
      - "*.o"
  script:
    file: ../build.sh
    env:
      PYTHON_VARIANT: "tsan-free-threading"

# derived from https://github.com/conda-forge/python-feedstock/blob/main/recipe/meta.yaml
requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - make
    - pkg-config
    # configure script looks for llvm-ar for lto
    - if: osx
      then:
        - llvm-tools
    - if: linux
      then:
        - ld_impl_${{ target_platform }}
        - binutils_impl_${{ target_platform }}
    - clang-19
    - llvm-tools-19

  host:
    - bzip2
    - sqlite
    - liblzma-devel
    - zlib
    - zstd
    - openssl
    - readline
    - tk
    # These two are just to get the headers needed for tk.h, but is unused
    - xorg-libx11
    - xorg-xorgproto
    - ncurses
    - libffi
    - if: linux
      then:
        - ld_impl_${{ target_platform }}
        - libuuid
    - libmpdec-devel
    - expat

about:
  homepage: https://www.python.org/
  license: Python-2.0
  license_file: LICENSE
