extend = "../../.ruff.toml"  # Inherit the project-wide settings

extend-exclude = [
    # Generated files:
    "Tools/peg_generator/pegen/grammar_parser.py",
]

[lint]
select = [
    "F",       # pyflakes
    "I",       # isort
    "UP",      # pyupgrade
    "RUF100",  # Ban unused `# noqa` comments
    "PGH004",  # Ban blanket `# noqa` comments (only ignore specific error codes)
]
ignore = [
    # Use PEP-604 unions rather than tuples for isinstance() checks.
    # Makes code slower and more verbose. https://github.com/astral-sh/ruff/issues/7871.
    "UP038",
]
unfixable = [
    # The autofixes sometimes do the wrong things for these;
    # it's better to have to manually look at the code and see how it needs fixing
    "F841",  # Detects unused variables
    "F601",  # Detects dictionaries that have duplicate keys
    "F602",  # Also detects dictionaries that have duplicate keys
]
