#! /usr/bin/env python

import sys as _sys

# See if we are being asked to execute the subprocess code
if '-p' in _sys.argv:
    # run expects only the port number in _sys.argv
    _sys.argv.remove('-p')

    # this module will become the namepsace used by the interactive
    # interpreter; remove all variables we have defined.
    del _sys
    __import__('run').main()
else:
    # Start the IDLE GUI
    import PyShell
    PyShell.main()
