name: Documentation
description: Report a problem with the documentation
labels: ["docs"]
body:
  - type: markdown
    attributes:
      value: |
        If the issue is trivial, for example a typo, an issue is not necessary.
  - type: textarea
    attributes:
      label: "Documentation"
      description: "A clear and concise description of the issue."
    validations:
      required: true
