#! /bin/sh
case `uname -sr` in
'SunOS 5.'*)	;;
*)	echo Probably not on a Solaris 2 system 1>&2
	exit 1;;
esac
set -v
h2py -i '(u_long)' /usr/include/sys/types.h /usr/include/netinet/in.h /usr/include/sys/stropts.h /usr/include/dlfcn.h

