[package]
name = "cpython"
version = "3.12.3"
nanvix-version = "0.12.439"

[builds]
[builds.matrix]
platforms = ["microvm"]
modes = ["multi-process", "single-process", "standalone"]
memory = ["256mb"]

[dependencies]
zlib = "1.3.1"
sqlite = "3.49.0"
openssl = "3.5.0"
bzip2 = "1.0.8"
libffi = "3.4.6"
