"""
Generate enumeration for XSAVE state components (XCR0 control register).

See https://en.wikipedia.org/wiki/Control_register#XCR0_and_XSS.

.. seealso:: :file:`Include/internal/pycore_cpuinfo_xsave_features.h`
"""

from __future__ import annotations

__all__ = ["generate_xsave_features_enum"]

from typing import TYPE_CHECKING

from . import _util as util
from ._util import DOXYGEN_STYLE

if TYPE_CHECKING:
    from typing import Final

    type Feature = str
    type BitIndex = int

XSAVE_FEATURES: Final[dict[Feature, BitIndex]] = {
    "SSE": 1,
    "AVX": 2,
    "AVX512_OPMASK": 5,
    "AVX512_ZMM_HI256": 6,
    "AVX512_HI16_ZMM": 7,
}


def get_member_name(feature: Feature) -> str:
    return f"_Py_XSAVE_MASK_XCR0_{feature}"


_NAME_MAXSIZE: Final[int] = util.next_block(
    max(map(len, map(get_member_name, XSAVE_FEATURES)))
)


def generate_xsave_features_enum(enum_name: str) -> str:
    """Used by :file:`Include/internal/pycore_cpuinfo_xsave_features.h`.

    The C enumeration is generated by this function and Argument Clinic,
    to be eventually rendred as follows:

        <INDENT><MEMBER_NAME> <TAB>= 0x<MASK>, <TAB>// bit = BIT
        ^       ^             ^    ^   ^       ^    ^

    where ^ indicates a column that is a multiple of 4, <MASK> has
    exactly 8 characters and <BIT> has at most 2 characters.
    """
    enum_name, _typedef_enum_name = util.make_enum_name(enum_name)
    writer = util.CWriter()
    writer.comment("Enumeration for XSAVE components", style=DOXYGEN_STYLE)
    writer.write(f"enum {enum_name} {{")
    for feature_name, bit in XSAVE_FEATURES.items():
        if not 0 <= bit < 32:
            raise ValueError(f"invalid bit value for {feature_name!r}")
        key = get_member_name(feature_name)
        member_def = util.make_enum_member(key, bit, _NAME_MAXSIZE)
        writer.write(member_def, level=1)
    writer.write("};")
    return writer.build()
