# Generated from 'WASTE.h'

kPascalStackBased = None # workaround for header parsing
def FOUR_CHAR_CODE(x): return x
weCantUndoErr = -10015
weEmptySelectionErr = -10013
weUnknownObjectTypeErr = -9478
weObjectNotFoundErr = -9477
weReadOnlyErr = -9476
weTextNotFoundErr = -9474
weInvalidTextEncodingErr = -9473
weDuplicateAttributeErr = -9472
weInvalidAttributeSizeErr = -9471
weReadOnlyAttributeErr = -9470
weOddByteCountErr = -9469
weHandlerNotFoundErr = -1717
weNotHandledErr = -1708
weNewerVersionErr = -1706
weCorruptDataErr = -1702
weProtocolErr = -603
weUndefinedSelectorErr = -50
weFlushLeft = -2
weFlushRight = -1
weFlushDefault = 0
weCenter = 1
weJustify = 2
weDirDefault = 1
weDirRightToLeft = -1
weDirLeftToRight = 0
weDoFont = 0x0001
weDoFace = 0x0002
weDoSize = 0x0004
weDoColor = 0x0008
weDoAll = weDoFont | weDoFace | weDoSize | weDoColor
weDoAddSize = 0x0010
weDoToggleFace = 0x0020
weDoReplaceFace = 0x0040
weDoPreserveScript = 0x0080
weDoExtractSubscript = 0x0100
weDoFaceMask = 0x0200
weDoDirection = 0x00000001
weDoAlignment = 0x00000002
weDoLeftIndent = 0x00000004
weDoRightIndent = 0x00000008
weDoFirstLineIndent = 0x00000010
weDoLineSpacing = 0x00000020
weDoSpaceBefore = 0x00000040
weDoSpaceAfter = 0x00000080
weDoBottomBorderStyle = 0x00000400
kLeadingEdge = -1
kTrailingEdge = 0
kObjectEdge = 2
weFAutoScroll = 0
weFAutoIdle = 1
weFOutlineHilite = 2
weFReadOnly = 5
weFUndo = 6
weFIntCutAndPaste = 7
weFDragAndDrop = 8
weFInhibitRecal = 9
weFUseTempMem = 10
weFDrawOffscreen = 11
weFInhibitRedraw = 12
weFMonoStyled = 13
weFMultipleUndo = 14
weFLeftMarginClick = 16
weFNoAutoTabForHangingIndent = 28
weFNoKeyboardSync = 29
weFInhibitICSupport = 30
weFInhibitColor = 31
# weDoAutoScroll = 1UL << weFAutoScroll
weDoAutoIdle = 1UL << weFAutoIdle
# weDoOutlineHilite = 1UL << weFOutlineHilite
# weDoReadOnly = 1UL << weFReadOnly
# weDoUndo = 1UL << weFUndo
# weDoIntCutAndPaste = 1UL << weFIntCutAndPaste
# weDoDragAndDrop = 1UL << weFDragAndDrop
# weDoInhibitRecal = 1UL << weFInhibitRecal
# weDoUseTempMem = 1UL << weFUseTempMem
# weDoDrawOffscreen = 1UL << weFDrawOffscreen
# weDoInhibitRedraw = 1UL << weFInhibitRedraw
# weDoMonoStyled = 1UL << weFMonoStyled
# weDoMultipleUndo = 1UL << weFMultipleUndo
weDoLeftMarginClick = 1UL << weFLeftMarginClick
weDoNoAutoTabForHangingIndent = 1UL << weFNoAutoTabForHangingIndent
# weDoNoKeyboardSync = 1UL << weFNoKeyboardSync
# weDoInhibitICSupport = 1UL << weFInhibitICSupport
# weDoInhibitColor = 1UL << weFInhibitColor
weBitToggle = -2
weBitTest = -1
weBitClear = 0
weBitSet = 1
weLowerCase = 0
weUpperCase = 1
weRedWigglyUnderline = 29303
weGreenWigglyUnderline = 26487
weOrangeWigglyUnderline = 28535
weFindWholeWords = 0x00000001
weFindCaseInsensitive = 0x00000002
weFindDiacriticalInsensitive = 0x00000004
wePutIntCutAndPaste = 0x00000001
wePutAddToTypingSequence = 0x00000002
wePutDetectUnicodeBOM = 0x00000200
weStreamDestinationKindMask = 0x000000FF
weStreamIncludeObjects = 0x00000100
weCopyPromiseFlavors = 0x00000001
weGetAddUnicodeBOM = 0x00000200
weGetLittleEndian = 0x00000400
weSaveAddResources = 0x00000001
weSaveCompatibilityResources = 0x00000002
weSaveLittleEndian = 0x00000004
kWASTECreator = FOUR_CHAR_CODE('OEDE')
weTagFontFamily = FOUR_CHAR_CODE('font')
weTagFontSize = FOUR_CHAR_CODE('ptsz')
weTagPlain = FOUR_CHAR_CODE('plan')
weTagBold = FOUR_CHAR_CODE('bold')
weTagItalic = FOUR_CHAR_CODE('ital')
weTagUnderline = FOUR_CHAR_CODE('undl')
weTagOutline = FOUR_CHAR_CODE('outl')
weTagShadow = FOUR_CHAR_CODE('shad')
weTagCondensed = FOUR_CHAR_CODE('cond')
weTagExtended = FOUR_CHAR_CODE('pexp')
weTagStrikethrough = FOUR_CHAR_CODE('strk')
weTagHidden = FOUR_CHAR_CODE('hidn')
weTagAllCaps = FOUR_CHAR_CODE('alcp')
weTagAllLowercase = FOUR_CHAR_CODE('lowc')
weTagTextColor = FOUR_CHAR_CODE('colr')
weTagBackgroundColor = FOUR_CHAR_CODE('pbcl')
weTagTransferMode = FOUR_CHAR_CODE('pptm')
weTagVerticalShift = FOUR_CHAR_CODE('xshf')
weTagLanguage = FOUR_CHAR_CODE('lang')
weTagUnderlineStyle = FOUR_CHAR_CODE('unds')
weTagSmallCaps = FOUR_CHAR_CODE('smcp')
weTagDoubleStrikethrough = FOUR_CHAR_CODE('dstr')
weTagEmbossed = FOUR_CHAR_CODE('embo')
weTagEngraved = FOUR_CHAR_CODE('engr')
weTagAlignment = FOUR_CHAR_CODE('pjst')
weTagDirection = FOUR_CHAR_CODE('LDIR')
weTagLineSpacing = FOUR_CHAR_CODE('ledg')
weTagLeftIndent = FOUR_CHAR_CODE('lein')
weTagRightIndent = FOUR_CHAR_CODE('riin')
weTagFirstLineIndent = FOUR_CHAR_CODE('fidt')
weTagSpaceBefore = FOUR_CHAR_CODE('spbe')
weTagSpaceAfter = FOUR_CHAR_CODE('spaf')
weTagTabList = FOUR_CHAR_CODE('tabs')
weTagBottomBorderStyle = FOUR_CHAR_CODE('BBRD')
weTagKeepTogether = FOUR_CHAR_CODE('keep')
weTagKeepWithNext = FOUR_CHAR_CODE('kepn')
weTagPageBreakBefore = FOUR_CHAR_CODE('pbrb')
weTagWidowOrphanOverride = FOUR_CHAR_CODE('wdov')
weTagWidowOrphanControl = FOUR_CHAR_CODE('wido')
weTagNoLineNumbering = FOUR_CHAR_CODE('!ln#')
weTagNoHyphenation = FOUR_CHAR_CODE('!hyp')
weTagParagraphUserData = FOUR_CHAR_CODE('pusr')
weTagForceFontFamily = FOUR_CHAR_CODE('ffnt')
weTagAddFontSize = FOUR_CHAR_CODE('+siz')
weTagAddVerticalShift = FOUR_CHAR_CODE('+shf')
weTagAddLeftIndent = FOUR_CHAR_CODE('+lei')
weTagAddRightIndent = FOUR_CHAR_CODE('+rii')
weTagAddFirstLineIndent = FOUR_CHAR_CODE('+fid')
weTagAddSpaceBefore = FOUR_CHAR_CODE('+spb')
weTagAddSpaceAfter = FOUR_CHAR_CODE('+spa')
weTagAddLineSpacing = FOUR_CHAR_CODE('+led')
weTagTextEncoding = FOUR_CHAR_CODE('ptxe')
weTagQDStyles = FOUR_CHAR_CODE('qdst')
weTagTETextStyle = FOUR_CHAR_CODE('tets')
weTagRunDirection = FOUR_CHAR_CODE('rdir')
weTagUnderlineDefault = FOUR_CHAR_CODE('deft')
weTagUnderlineWord = FOUR_CHAR_CODE('word')
weTagUnderlineDouble = FOUR_CHAR_CODE('dubl')
weTagUnderlineThick = FOUR_CHAR_CODE('thck')
weTagUnderlineDash = FOUR_CHAR_CODE('-   ')
weTagUnderlineDot = FOUR_CHAR_CODE('.   ')
weTagUnderlineDotDash = FOUR_CHAR_CODE('.-  ')
weTagUnderlineDotDotDash = FOUR_CHAR_CODE('..- ')
weTagUnderlineWave = FOUR_CHAR_CODE('wave')
weTagAlignmentDefault = FOUR_CHAR_CODE('deft')
weTagAlignmentLeft = FOUR_CHAR_CODE('left')
weTagAlignmentCenter = FOUR_CHAR_CODE('cent')
weTagAlignmentRight = FOUR_CHAR_CODE('rght')
weTagAlignmentFull = FOUR_CHAR_CODE('full')
weTagAlignmentDecimal = FOUR_CHAR_CODE('decm')
weTagDirectionDefault = FOUR_CHAR_CODE('deft')
weTagDirectionLeftToRight = FOUR_CHAR_CODE('L->R')
weTagDirectionRightToLeft = FOUR_CHAR_CODE('R->L')
weTagLeaderNone = FOUR_CHAR_CODE('NONE')
weTagLeaderDots = FOUR_CHAR_CODE('DOTS')
weTagLeaderHyphens = FOUR_CHAR_CODE('HYPH')
weTagLeaderUnderline = FOUR_CHAR_CODE('UNDL')
weTagLeaderThickLine = FOUR_CHAR_CODE('THKL')
weTagLeaderEqualSigns = FOUR_CHAR_CODE('=   ')
weTagBorderStyleNone = FOUR_CHAR_CODE('NONE')
weTagBorderStyleThin = FOUR_CHAR_CODE('SLDL')
weTagBorderStyleDotted = FOUR_CHAR_CODE('DTDL')
weTagBorderStyleThick = FOUR_CHAR_CODE('THKL')
weTagLineSpacingAbsolute = FOUR_CHAR_CODE('abso')
weTagLineSpacingAtLeast = FOUR_CHAR_CODE('atle')
weTagLineSpacingRelative = FOUR_CHAR_CODE('rele')
weLineSpacingSingle = 0x00000000
weLineSpacingOneAndHalf = 0x00008000
weLineSpacingDouble = 0x00010000
weAutoScrollDelay = FOUR_CHAR_CODE('ausd')
weBusyProc = FOUR_CHAR_CODE('busy')
weBusyInterval = FOUR_CHAR_CODE('bzin')
weCharByteHook = FOUR_CHAR_CODE('cbyt')
weCharToPixelHook = FOUR_CHAR_CODE('c2p ')
weCharTypeHook = FOUR_CHAR_CODE('ctyp')
weClickLoop = FOUR_CHAR_CODE('clik')
weCurrentDrag = FOUR_CHAR_CODE('drag')
weDrawTextHook = FOUR_CHAR_CODE('draw')
weDrawTSMHiliteHook = FOUR_CHAR_CODE('dtsm')
weEraseHook = FOUR_CHAR_CODE('eras')
weFontFamilyToNameHook = FOUR_CHAR_CODE('ff2n')
weFontNameToFamilyHook = FOUR_CHAR_CODE('fn2f')
weFluxProc = FOUR_CHAR_CODE('flux')
weHiliteDropAreaHook = FOUR_CHAR_CODE('hidr')
weLineBreakHook = FOUR_CHAR_CODE('lbrk')
wePixelToCharHook = FOUR_CHAR_CODE('p2c ')
wePort = FOUR_CHAR_CODE('port')
wePreTrackDragHook = FOUR_CHAR_CODE('ptrk')
weRefCon = FOUR_CHAR_CODE('refc')
weScrollProc = FOUR_CHAR_CODE('scrl')
weText = FOUR_CHAR_CODE('text')
weTranslateDragHook = FOUR_CHAR_CODE('xdrg')
weTranslucencyThreshold = FOUR_CHAR_CODE('tluc')
weTSMDocumentID = FOUR_CHAR_CODE('tsmd')
weTSMPreUpdate = FOUR_CHAR_CODE('pre ')
weTSMPostUpdate = FOUR_CHAR_CODE('post')
weUndoProc = FOUR_CHAR_CODE('undo')
weURLHint = FOUR_CHAR_CODE('urlh')
weWordBreakHook = FOUR_CHAR_CODE('wbrk')
weNewHandler = FOUR_CHAR_CODE('new ')
weDisposeHandler = FOUR_CHAR_CODE('free')
weDrawHandler = FOUR_CHAR_CODE('draw')
weClickHandler = FOUR_CHAR_CODE('clik')
weStreamHandler = FOUR_CHAR_CODE('strm')
weHoverHandler = FOUR_CHAR_CODE('hovr')
kTypeText = FOUR_CHAR_CODE('TEXT')
kTypeStyles = FOUR_CHAR_CODE('styl')
kTypeSoup = FOUR_CHAR_CODE('SOUP')
kTypeFontTable = FOUR_CHAR_CODE('FISH')
kTypeParaFormat = FOUR_CHAR_CODE('WEpf')
kTypeRulerScrap = FOUR_CHAR_CODE('WEru')
kTypeCharFormat = FOUR_CHAR_CODE('WEcf')
kTypeStyleScrap = FOUR_CHAR_CODE('WEst')
kTypeUnicodeText = FOUR_CHAR_CODE('utxt')
kTypeUTF8Text = FOUR_CHAR_CODE('UTF8')
kTypeStyledText = FOUR_CHAR_CODE('STXT')
kTypeRTF = FOUR_CHAR_CODE('RTF ')
kTypeRTFD = FOUR_CHAR_CODE('RTFD')
weAKNone = 0
weAKUnspecified = 1
weAKTyping = 2
weAKCut = 3
weAKPaste = 4
weAKClear = 5
weAKDrag = 6
weAKSetStyle = 7
weAKSetRuler = 8
weAKBackspace = 9
weAKFwdDelete = 10
weAKCaseChange = 11
weAKObjectChange = 12
weUndoNewAction = 0
weUndoNewSubAction = 1
weUndoBeginSequence = 2
weToScrap = 0
weToDrag = 1
weToSoup = 2
weMouseEnter = 0
weMouseWithin = 1
weMouseLeave = 2
weBusyRecalBreaks = 0
weCreatorDocumentInfo = FOUR_CHAR_CODE('Info')
weTagDocumentTitle = FOUR_CHAR_CODE('Titl')
weTagDocumentSubject = FOUR_CHAR_CODE('Subj')
weTagDocumentAuthor = FOUR_CHAR_CODE('Auth')
weTagDocumentManager = FOUR_CHAR_CODE('Mngr')
weTagDocumentCompany = FOUR_CHAR_CODE('Cmpy')
weTagDocumentCategory = FOUR_CHAR_CODE('Ctgy')
weTagDocumentKeywords = FOUR_CHAR_CODE('Keyw')
weTagDocumentComments = FOUR_CHAR_CODE('Cmnt')
weTagDocumentOperator = FOUR_CHAR_CODE('Oper')
weTagDocumentBaseAddress = FOUR_CHAR_CODE('Hlnk')
weTagPageInfo = FOUR_CHAR_CODE('Page')
weTagMacPrintRecord = FOUR_CHAR_CODE('PRec')
kCurrentSelection = -1
kNullStyle = -2
kMaxTabCount = 20
kMaxLanguageTagSize = 32
