# NOTE: Please always only modify default/recipe.yaml and then run clone-recipe.sh to
# propagate the changes to the other variants.

context:
  # Keep up to date
  freethreading_tag: ${{ "t" if "freethreading" in variant else "" }}

recipe:
  name: python

source:
  - path: ../../..

outputs:
- package:
    name: python_abi
    version: ${{ version }}
  build:
    string: "0_${{ abi_tag }}"
  requirements:
    run_constraints:
      - python ${{ version }}.* *_${{ abi_tag }}

- package:
    name: python
    version: ${{ version }}
  build:
    string: "0_${{ abi_tag }}"
    files:
      exclude:
        - "*.o"
    script:
      file: ../build.sh
      env:
        PYTHON_VARIANT: ${{ variant }}
    python:
      site_packages_path: "lib/python${{ version }}${{ freethreading_tag }}/site-packages"

  # derived from https://github.com/conda-forge/python-feedstock/blob/main/recipe/meta.yaml
  requirements:
    build:
      - ${{ compiler('c') }}
      - ${{ compiler('cxx') }}
      # Note that we are not using stdlib arguments which means the packages
      # are built for the build settings and are not relocatable to a different
      # machine that has a older system version. (eg: macOS/glibc version)
      - make
      - pkg-config
      # configure script looks for llvm-ar for lto
      - if: osx
        then:
          - llvm-tools

    host:
      - bzip2
      - sqlite
      - liblzma-devel
      - zlib
      - zstd
      - openssl
      - readline
      - tk
      # These two are just to get the headers needed for tk.h, but is unused
      - xorg-libx11
      - xorg-xorgproto
      - ncurses
      - libffi
      - if: linux
        then:
          - libuuid
      - libmpdec-devel
      - expat
      - if: linux and "san" in variant
        then:
          - libsanitizer
      - if: osx and "san" in variant
        then:
          - libcompiler-rt

    ignore_run_exports:
      from_package:
        - xorg-libx11
        - xorg-xorgproto

    run_exports:
      noarch:
        - python
      weak:
        - python_abi ${{ version }}.* *_${{ abi_tag }}

about:
  homepage: https://www.python.org/
  license: Python-2.0
  license_file: LICENSE
