#! /bin/sh
case `uname -sv` in
'AIX 4'*)  ;;
*)      echo Probably not on an AIX 4 system 1>&2
        exit 1;;
esac
set -v
h2py.py /usr/include/fcntl.h
h2py.py /usr/include/sys/socket.h
h2py.py -i '(u_long)' /usr/include/netinet/in.h
h2py.py /usr/include/termios.h
