#! /bin/sh
case `uname` in
Linux*)	;;
*)	echo Probably not on a Linux system 1>&2
	exit 1;;
esac
set -v
h2py /usr/include/sys/fcntl.h
h2py /usr/include/sys/socket.h
h2py -i '(u_long)' /usr/include/netinet/in.h
h2py /usr/include/termios.h
