svTempDisable	=	-32768	#svTempDisable
svDisabled	=	-32640	#Reserve range -32640 to -32768 for Apple temp disables.
fontNotOutlineErr	=	-32615	#bitmap font passed to routine that does outlines only
noMemoryNodeFailedInitialize	=	-30552	#noMemoryNodeFailedInitialize
invalidHotSpotIDErr	=	-30551	#invalidHotSpotIDErr
invalidNodeFormatErr	=	-30550	#invalidNodeFormatErr
limitReachedErr	=	-30549	#limitReachedErr
settingNotSupportedByNodeErr	=	-30548	#settingNotSupportedByNodeErr
propertyNotSupportedByNodeErr	=	-30547	#propertyNotSupportedByNodeErr
timeNotInViewErr	=	-30546	#timeNotInViewErr
invalidViewStateErr	=	-30545	#invalidViewStateErr
invalidNodeIDErr	=	-30544	#invalidNodeIDErr
selectorNotSupportedByNodeErr	=	-30543	#selectorNotSupportedByNodeErr
callNotSupportedByNodeErr	=	-30542	#callNotSupportedByNodeErr
constraintReachedErr	=	-30541	#constraintReachedErr
notAQTVRMovieErr	=	-30540	#notAQTVRMovieErr
kALMInternalErr	=	-30049	#kALMInternalErr
kALMLocationNotFoundErr	=	-30048	#kALMLocationNotFoundErr
kALMNoSuchModuleErr	=	-30047	#kALMNoSuchModuleErr
kALMModuleCommunicationErr	=	-30046	#kALMModuleCommunicationErr
kALMDuplicateModuleErr	=	-30045	#kALMDuplicateModuleErr
kALMInstallationErr	=	-30044	#kALMInstallationErr
kALMDeferSwitchErr	=	-30043	#kALMDeferSwitchErr
kALMRebootFlagsLevelErr	=	-30042	#kALMRebootFlagsLevelErr
localeNoAssociatedDataTagsErr	=	-30027	#localeNoAssociatedDataTagsErr
localeObjectDefaultValueNotAvailableErr	=	-30026	#localeObjectDefaultValueNotAvailableErr
localeDuplicateErr	=	-30025	#localeDuplicateErr
localeCouldNotWriteLinkedObjectsErr	=	-30024	#localeCouldNotWriteLinkedObjectsErr
localeObjectCannotDeleteSystemObjectErr	=	-30023	#localeObjectCannotDeleteSystemObjectErr
localeObjectTagDataNotFoundErr	=	-30022	#localeObjectTagDataNotFoundErr
localeObjectNoNameErr	=	-30021	#localeObjectNoNameErr
localeObjectInvalidIteratorErr	=	-30020	#localeObjectInvalidIteratorErr
localeObjectNameAttributeConflictErr	=	-30010	#localeObjectNameAttributeConflictErr
localeObjectItemFoundIsLastErr	=	-30009	#localeObjectItemFoundIsLastErr
localeObjectInvalidReferenceErr	=	-30008	#localeObjectInvalidReferenceErr
localeObjectNotFoundErr	=	-30007	#localeObjectNotFoundErr
localeBadReferenceErr	=	-30006	#localeBadReferenceErr
localeObjectNoNamesTableErr	=	-30005	#localeObjectNoNamesTableErr
localeObjectAttributeNotAvailErr	=	-30002	#localeObjectAttributeNotAvailErr
localeNotFoundErr	=	-30001	#localeNotFoundErr
logCorruptStoreErr	=	-29898	#logCorruptStoreErr
logInvalidSituationTypeErr	=	-29897	#logInvalidSituationTypeErr
logIteratorInvalidErr	=	-29896	#logIteratorInvalidErr
logCannotCreateActionErr	=	-29895	#logCannotCreateActionErr
logEntryCorruptErr	=	-29894	#logEntryCorruptErr
logWrongTypeErr	=	-29893	#logWrongTypeErr
logPluginNotPresentErr	=	-29892	#logPluginNotPresentErr
logInvalidSizeErr	=	-29891	#logInvalidSizeErr
logNoDataAvailableErr	=	-29890	#logNoDataAvailableErr
logNotATextEntryErr	=	-29889	#logNotATextEntryErr
logIteratorInUseErr	=	-29888	#logIteratorInUseErr
logServiceNotInUseErr	=	-29887	#logServiceNotInUseErr
logQueueFullErr	=	-29886	#logQueueFullErr
logNoMoreEntriesErr	=	-29885	#logNoMoreEntriesErr
logServiceInUseErr	=	-29884	#logServiceInUseErr
logNoSuchActionErr	=	-29883	#logNoSuchActionErr
logInvalidVersionErr	=	-29882	#logInvalidVersionErr
logDataTooLargeErr	=	-29881	#logDataTooLargeErr
logNoConnectionErr	=	-29880	#logNoConnectionErr
textObjFontNotFoundErr	=	-29599	#textObjFontNotFoundErr
textObjLanguageChangedErr	=	-29587	#textObjLanguageChangedErr
textObjMoreAnnotationsErr	=	-29586	#textObjMoreAnnotationsErr
textObjAnnotationNotFoundErr	=	-29585	#textObjAnnotationNotFoundErr
textObjMalformedObjectErr	=	-29584	#textObjMalformedObjectErr
textObjTextConversionFailedErr	=	-29583	#textObjTextConversionFailedErr
textObjObjectTooSmallErr	=	-29582	#textObjObjectTooSmallErr
textObjBufferTooSmallErr	=	-29581	#textObjBufferTooSmallErr
textObjInvalidIndexErr	=	-29580	#textObjInvalidIndexErr
kCollateInvalidCollationRef	=	-29507	#kCollateInvalidCollationRef
kCollateBufferTooSmall	=	-29506	#kCollateBufferTooSmall
kCollateInvalidChar	=	-29505	#kCollateInvalidChar
kCollatePatternNotFoundErr	=	-29504	#kCollatePatternNotFoundErr
kCollateUnicodeConvertFailedErr	=	-29503	#kCollateUnicodeConvertFailedErr
kCollateMissingUnicodeTableErr	=	-29502	#kCollateMissingUnicodeTableErr
kCollateInvalidOptions	=	-29501	#kCollateInvalidOptions
kCollateAttributesNotFoundErr	=	-29500	#kCollateAttributesNotFoundErr
kMPInvalidIDErr	=	-29299	#kMPInvalidIDErr
kMPInsufficientResourcesErr	=	-29298	#kMPInsufficientResourcesErr
kMPTaskAbortedErr	=	-29297	#kMPTaskAbortedErr
kMPTimeoutErr	=	-29296	#kMPTimeoutErr
kMPDeletedErr	=	-29295	#kMPDeletedErr
invalidIndexErr	=	-20002	#The recordIndex parameter is not valid.
recordDataTooBigErr	=	-20001	#The record data is bigger than buffer size (1024 bytes).
unknownInsertModeErr	=	-20000	#There is no such an insert mode.
pmRecvEndErr	=	-13005	#during receive, pmgr did not finish hs configured for this connection
pmRecvStartErr	=	-13004	#during receive, pmgr did not start hs
pmSendEndErr	=	-13003	#during send, pmgr did not finish hs
pmSendStartErr	=	-13002	#during send, pmgr did not start hs
pmReplyTOErr	=	-13001	#Timed out waiting for reply
pmBusyErr	=	-13000	#Power Mgr never ready to start handshake
pictureDataErr	=	-11005	#the picture data was invalid
colorsRequestedErr	=	-11004	#the number of colors requested was illegal
cantLoadPickMethodErr	=	-11003	#unable to load the custom pick proc
pictInfoVerbErr	=	-11002	#the passed verb was invalid
pictInfoIDErr	=	-11001	#the internal consistancy check for the PictInfoID is wrong
pictInfoVersionErr	=	-11000	#wrong version of the PictInfo structure
telNotEnoughdspBW	=	-10116	#not enough real-time for allocation
telBadSampleRate	=	-10115	#incompatible sample rate
telBadSWErr	=	-10114	#Software not installed properly
telDetAlreadyOn	=	-10113	#detection is already turned on
telAutoAnsNotOn	=	-10112	#autoAnswer in not turned on
telValidateFailed	=	-10111	#telValidate failed
telBadProcID	=	-10110	#invalid procID
telDeviceNotFound	=	-10109	#device not found
telBadCodeResource	=	-10108	#code resource not found
telInitFailed	=	-10107	#initialization failed
telNoCommFolder	=	-10106	#Communications/Extensions Ÿ not found
telUnknownErr	=	-10103	#unable to set config
telNoSuchTool	=	-10102	#unable to find tool with name specified
telBadFunction	=	-10091	#bad msgCode specified
telPBErr	=	-10090	#parameter block error, bad format
telCANotDeflectable	=	-10082	#CA not "deflectable"
telCANotRejectable	=	-10081	#CA not "rejectable"
telCANotAcceptable	=	-10080	#CA not "acceptable"
telTermNotOpen	=	-10072	#terminal not opened via TELOpenTerm
telStillNeeded	=	-10071	#terminal driver still needed by someone else
telAlreadyOpen	=	-10070	#terminal already open
telNoCallbackRef	=	-10064	#no call back reference was specified, but is required
telDisplayModeNotSupp	=	-10063	#display mode not supported by tool
telBadDisplayMode	=	-10062	#bad display mode specified
telFwdTypeNotSupp	=	-10061	#forward type not supported by tool
telDNTypeNotSupp	=	-10060	#DN type not supported by tool
telBadRate	=	-10059	#bad rate specified
telBadBearerType	=	-10058	#bad bearerType specified
telBadSelect	=	-10057	#unable to select or deselect DN
telBadParkID	=	-10056	#bad park id specified
telBadPickupGroupID	=	-10055	#bad pickup group ID specified
telBadFwdType	=	-10054	#bad fwdType specified
telBadFeatureID	=	-10053	#bad feature ID specified
telBadIntercomID	=	-10052	#bad intercom ID specified
telBadPageID	=	-10051	#bad page ID specified
telBadDNType	=	-10050	#DN type invalid
telConfLimitExceeded	=	-10047	#attempt to exceed switch conference limits
telCBErr	=	-10046	#call back feature not set previously
telTransferRej	=	-10045	#transfer request rejected
telTransferErr	=	-10044	#transfer not prepared
telConfRej	=	-10043	#conference request was rejected
telConfErr	=	-10042	#conference was not prepared
telConfNoLimit	=	-10041	#no limit was specified but required
telConfLimitErr	=	-10040	#limit specified is too high for this configuration
telFeatNotSupp	=	-10033	#feature program call not supported by this tool
telFeatActive	=	-10032	#feature already active
telFeatNotAvail	=	-10031	#feature subscribed but not available
telFeatNotSub	=	-10030	#feature not subscribed
telDNDTypeNotSupp	=	-10024	#DND type is not supported by this tool
telBadDNDType	=	-10023	#bad DND type specified
telIntExtNotSupp	=	-10022	#internal external type not supported by this tool
telBadIntExt	=	-10021	#bad internal external error
telStateNotSupp	=	-10020	#device state not supported by tool
telBadStateErr	=	-10019	#bad device state specified
telIndexNotSupp	=	-10018	#index not supported by this tool
telBadIndex	=	-10017	#bad index specified
telAPattNotSupp	=	-10016	#alerting pattern not supported by tool
telBadAPattErr	=	-10015	#bad alerting pattern specified
telVTypeNotSupp	=	-10014	#volume type not supported by this tool
telBadVTypeErr	=	-10013	#bad volume type error
telBadLevelErr	=	-10012	#bad volume level setting
telHTypeNotSupp	=	-10011	#hook type not supported by this tool
telBadHTypeErr	=	-10010	#bad hook type specified
errAECantSupplyType	=	-10009	#errAECantSupplyType
telNoOpenErr	=	-10008	#unable to open terminal
telNoMemErr	=	-10007	#no memory to allocate handle
telCAUnavail	=	-10006	#a CA is not available
telBadProcErr	=	-10005	#bad msgProc specified
telBadHandErr	=	-10004	#bad handle specified
telBadCAErr	=	-10003	#TELCAHandle not found or invalid
telBadDNErr	=	-10002	#TELDNHandle not found or invalid
telBadTermErr	=	-10001	#invalid TELHandle or handle not found
errAEEventFailed	=	-10000	#errAEEventFailed
cannotMoveAttachedController	=	-9999	#cannotMoveAttachedController
controllerHasFixedHeight	=	-9998	#controllerHasFixedHeight
cannotSetWidthOfAttachedController	=	-9997	#cannotSetWidthOfAttachedController
controllerBoundsNotExact	=	-9996	#controllerBoundsNotExact
editingNotAllowed	=	-9995	#editingNotAllowed
badControllerHeight	=	-9994	#badControllerHeight
deviceCantMeetRequest	=	-9408	#deviceCantMeetRequest
seqGrabInfoNotAvailable	=	-9407	#seqGrabInfoNotAvailable
badSGChannel	=	-9406	#badSGChannel
couldntGetRequiredComponent	=	-9405	#couldntGetRequiredComponent
notEnoughDiskSpaceToGrab	=	-9404	#notEnoughDiskSpaceToGrab
notEnoughMemoryToGrab	=	-9403	#notEnoughMemoryToGrab
cantDoThatInCurrentMode	=	-9402	#cantDoThatInCurrentMode
grabTimeComplete	=	-9401	#grabTimeComplete
noDeviceForChannel	=	-9400	#noDeviceForChannel
snsAlreadyUnheldErr	=	-9013	#snsAlreadyUnheldErr
snsReliabilityFailureErr	=	-9012	#snsReliabilityFailureErr
snsConsumerQueueOverrunErr	=	-9011	#snsConsumerQueueOverrunErr
snsBufferTooSmallErr	=	-9010	#snsBufferTooSmallErr
snsSubjectToLargeErr	=	-9009	#snsSubjectToLargeErr
snsNoSuchDistributorErr	=	-9008	#snsNoSuchDistributorErr
snsDuplicateDistributorErr	=	-9007	#snsDuplicateDistributorErr
snsDuplicateSubscriptionErr	=	-9006	#snsDuplicateSubscriptionErr
snsNoRequestsPendingErr	=	-9005	#snsNoRequestsPendingErr
snsQueueEmptyErr	=	-9004	#snsQueueEmptyErr
snsDistributorGoneErr	=	-9003	#snsDistributorGoneErr
snsNoSuchKindErr	=	-9002	#snsNoSuchKindErr
snsNoSuchSubscriptionErr	=	-9001	#snsNoSuchSubscriptionErr
snsNoSuchTypeErr	=	-9000	#snsNoSuchTypeErr
codecNoMemoryPleaseWaitErr	=	-8977	#codecNoMemoryPleaseWaitErr
codecNothingToBlitErr	=	-8976	#codecNothingToBlitErr
codecCantQueueErr	=	-8975	#codecCantQueueErr
codecCantWhenErr	=	-8974	#codecCantWhenErr
codecOpenErr	=	-8973	#codecOpenErr
codecConditionErr	=	-8972	#codecConditionErr
codecExtensionNotFoundErr	=	-8971	#codecExtensionNotFoundErr
codecDataVersErr	=	-8970	#codecDataVersErr
codecBadDataErr	=	-8969	#codecBadDataErr
codecWouldOffscreenErr	=	-8968	#codecWouldOffscreenErr
codecAbortErr	=	-8967	#codecAbortErr
codecSpoolErr	=	-8966	#codecSpoolErr
codecImageBufErr	=	-8965	#codecImageBufErr
codecScreenBufErr	=	-8964	#codecScreenBufErr
codecSizeErr	=	-8963	#codecSizeErr
codecUnimpErr	=	-8962	#codecUnimpErr
noCodecErr	=	-8961	#noCodecErr
codecErr	=	-8960	#codecErr
kTECOutputBufferFullStatus	=	-8785	#output buffer has no room for conversion of next input text element (partial conversion)
kTECNeedFlushStatus	=	-8784	#kTECNeedFlushStatus
kTECUsedFallbacksStatus	=	-8783	#kTECUsedFallbacksStatus
kTECItemUnavailableErr	=	-8771	#item (e.g. name) not available for specified region (& encoding if relevant)
kTECGlobalsUnavailableErr	=	-8770	#globals have already been deallocated (premature TERM)
unicodeChecksumErr	=	-8769	#unicodeChecksumErr
unicodeNoTableErr	=	-8768	#unicodeNoTableErr
unicodeVariantErr	=	-8767	#unicodeVariantErr
unicodeFallbacksErr	=	-8766	#unicodeFallbacksErr
unicodePartConvertErr	=	-8765	#unicodePartConvertErr
unicodeBufErr	=	-8764	#unicodeBufErr
unicodeCharErr	=	-8763	#unicodeCharErr
unicodeElementErr	=	-8762	#unicodeElementErr
unicodeNotFoundErr	=	-8761	#unicodeNotFoundErr
unicodeTableFormatErr	=	-8760	#unicodeTableFormatErr
unicodeDirectionErr	=	-8759	#unicodeDirectionErr
unicodeContextualErr	=	-8758	#unicodeContextualErr
unicodeTextEncodingDataErr	=	-8757	#unicodeTextEncodingDataErr
kTECDirectionErr	=	-8756	#direction stack overflow, etc.
kTECIncompleteElementErr	=	-8755	#text element may be incomplete or is too long for internal buffers
kTECUnmappableElementErr	=	-8754	#kTECUnmappableElementErr
kTECPartialCharErr	=	-8753	#input buffer ends in the middle of a multibyte character, conversion stopped
kTECBadTextRunErr	=	-8752	#kTECBadTextRunErr
kTECArrayFullErr	=	-8751	#supplied name buffer or TextRun, TextEncoding, or UnicodeMapping array is too small
kTECBufferBelowMinimumSizeErr	=	-8750	#output buffer too small to allow processing of first input text element
kTECNoConversionPathErr	=	-8749	#kTECNoConversionPathErr
kTECCorruptConverterErr	=	-8748	#invalid converter object reference
kTECTableFormatErr	=	-8747	#kTECTableFormatErr
kTECTableChecksumErr	=	-8746	#kTECTableChecksumErr
kTECMissingTableErr	=	-8745	#kTECMissingTableErr
kTextUndefinedElementErr	=	-8740	#text conversion errors
kTextMalformedInputErr	=	-8739	#in DBCS, for example, high byte followed by invalid low byte
kTextUnsupportedEncodingErr	=	-8738	#specified encoding not supported for this operation
kDMMainDisplayCannotMoveErr	=	-6231	#Trying to move main display (or a display mirrored to it)
kDMDisplayAlreadyInstalledErr	=	-6230	#Attempt to add an already installed display.
kDMDisplayNotFoundErr	=	-6229	#Could not find item (will someday remove).
kDMDriverNotDisplayMgrAwareErr	=	-6228	#Video Driver does not support display manager.
kDMSWNotInitializedErr	=	-6227	#Required software not initialized (eg windowmanager or display mgr).
kSysSWTooOld	=	-6226	#Missing critical pieces of System Software.
kDMMirroringNotOn	=	-6225	#Returned by all calls that need mirroring to be on to do their thing.
kDMCantBlock	=	-6224	#Mirroring is already on, can¹t Block now (call DMUnMirror() first).
kDMMirroringBlocked	=	-6223	#DMBlockMirroring() has been called.
kDMWrongNumberOfDisplays	=	-6222	#Can only handle 2 displays for now.
kDMMirroringOnAlready	=	-6221	#Returned by all calls that need mirroring to be off to do their thing.
kDMGenErr	=	-6220	#Unexpected Error
collectionVersionErr	=	-5753	#collectionVersionErr
collectionIndexRangeErr	=	-5752	#collectionIndexRangeErr
collectionItemNotFoundErr	=	-5751	#collectionItemNotFoundErr
collectionItemLockedErr	=	-5750	#collectionItemLockedErr
gestaltLocationErr	=	-5553	#gestalt function ptr wasn't in sysheap
gestaltDupSelectorErr	=	-5552	#tried to add an entry that already existed
gestaltUndefSelectorErr	=	-5551	#undefined selector was passed to Gestalt
gestaltUnknownErr	=	-5550	#value returned if Gestalt doesn't know the answer
envVersTooBig	=	-5502	#Version bigger than call can handle
envBadVers	=	-5501	#Version non-positive
envNotPresent	=	-5500	#returned by glue.
errCannotUndo	=	-5253	#errCannotUndo
errNonContiuousAttribute	=	-5252	#errNonContiuousAttribute
errUnknownElement	=	-5251	#errUnknownElement
errReadOnlyText	=	-5250	#errReadOnlyText
errEmptyScrap	=	-5249	#errEmptyScrap
errNoHiliteText	=	-5248	#errNoHiliteText
errOffsetNotOnElementBounday	=	-5247	#errOffsetNotOnElementBounday
errInvalidRange	=	-5246	#errInvalidRange
errIteratorReachedEnd	=	-5245	#errIteratorReachedEnd
errEngineNotFound	=	-5244	#errEngineNotFound
errAlreadyInImagingMode	=	-5243	#errAlreadyInImagingMode
errNotInImagingMode	=	-5242	#errNotInImagingMode
errMarginWilllNotFit	=	-5241	#errMarginWilllNotFit
errUnknownAttributeTag	=	-5240	#errUnknownAttributeTag
textParserNoMoreTokensErr	=	-5229	#textParserNoMoreTokensErr
textParserNoSuchTokenFoundErr	=	-5228	#textParserNoSuchTokenFoundErr
textParserBadTextEncodingErr	=	-5227	#textParserBadTextEncodingErr
textParserBadTextLanguageErr	=	-5226	#textParserBadTextLanguageErr
textParserNoMoreTextErr	=	-5225	#textParserNoMoreTextErr
textParserParamErr	=	-5224	#textParserParamErr
textParserBadParserObjectErr	=	-5223	#textParserBadParserObjectErr
textParserBadTokenValueErr	=	-5222	#textParserBadTokenValueErr
textParserObjectNotFoundErr	=	-5221	#textParserObjectNotFoundErr
textParserBadParamErr	=	-5220	#textParserBadParamErr
numberFortmattingNotADigitErr	=	-5212	#numberFortmattingNotADigitErr
numberFormattingBadCurrencyPositionErr	=	-5211	#numberFormattingBadCurrencyPositionErr
numberFormattingUnOrdredCurrencyRangeErr	=	-5210	#numberFormattingUnOrdredCurrencyRangeErr
numberFormattingBadTokenErr	=	-5209	#numberFormattingBadTokenErr
numberFormattingBadFormatErr	=	-5207	#numberFormattingBadFormatErr
numberFormattingEmptyFormatErr	=	-5206	#numberFormattingEmptyFormatErr
numberFormattingDelimiterMissingErr	=	-5205	#numberFormattingDelimiterMissingErr
numberFormattingLiteralMissingErr	=	-5204	#numberFormattingLiteralMissingErr
numberFormattingSpuriousCharErr	=	-5203	#numberFormattingSpuriousCharErr
numberFormattingBadNumberFormattingObjectErr	=	-5202	#numberFormattingBadNumberFormattingObjectErr
numberFormattingOverflowInDestinationErr	=	-5201	#numberFormattingOverflowInDestinationErr
numberFormattingNotANumberErr	=	-5200	#numberFormattingNotANumberErr
afpSameNodeErr	=	-5063	#Display Manager error codes (-6220...-6269)
afpAlreadyMounted	=	-5062	#afpAlreadyMounted
afpCantMountMoreSrvre	=	-5061	#afpCantMountMoreSrvre
afpBadDirIDType	=	-5060	#afpBadDirIDType
afpInsideTrashErr	=	-5044	#the folder being shared is inside the trash folder
afpInsideSharedErr	=	-5043	#the folder being shared is inside a shared folder OR the folder contains a shared folder and is being moved into a shared folder
afpPwdExpiredErr	=	-5042	#the password being used is too old: this requires the user to change the password before log-in can continue
afpPwdTooShortErr	=	-5041	#the password being set is too short: there is a minimum length that must be met or exceeded
afpPwdSameErr	=	-5040	#someone tried to change their password to the same password on a mantadory password change
afpBadIDErr	=	-5039	#afpBadIDErr
afpSameObjectErr	=	-5038	#afpSameObjectErr
afpCatalogChanged	=	-5037	#afpCatalogChanged
afpDiffVolErr	=	-5036	#afpDiffVolErr
afpIDExists	=	-5035	#afpIDExists
afpIDNotFound	=	-5034	#afpIDNotFound
afpContainsSharedErr	=	-5033	#the folder being shared contains a shared folder
afpObjectLocked	=	-5032	#Object is M/R/D/W inhibited
afpVolLocked	=	-5031	#Volume is Read-Only
afpIconTypeError	=	-5030	#afpIconTypeError
afpDirNotFound	=	-5029	#afpDirNotFound
numberFormattingBadOptionsErr	=	-5028	#numberFormattingBadOptionsErr
afpServerGoingDown	=	-5027	#afpServerGoingDown
afpTooManyFilesOpen	=	-5026	#afpTooManyFilesOpen
afpObjectTypeErr	=	-5025	#afpObjectTypeErr
afpCallNotSupported	=	-5024	#afpCallNotSupported
afpUserNotAuth	=	-5023	#afpUserNotAuth
afpSessClosed	=	-5022	#afpSessClosed
afpRangeOverlap	=	-5021	#afpRangeOverlap
afpRangeNotLocked	=	-5020	#afpRangeNotLocked
afpParmErr	=	-5019	#afpParmErr
afpObjectNotFound	=	-5018	#afpObjectNotFound
afpObjectExists	=	-5017	#afpObjectExists
afpNoServer	=	-5016	#afpNoServer
afpNoMoreLocks	=	-5015	#afpNoMoreLocks
afpMiscErr	=	-5014	#afpMiscErr
afpLockErr	=	-5013	#afpLockErr
afpItemNotFound	=	-5012	#afpItemNotFound
afpFlatVol	=	-5011	#afpFlatVol
afpFileBusy	=	-5010	#afpFileBusy
afpEofError	=	-5009	#afpEofError
afpDiskFull	=	-5008	#afpDiskFull
afpDirNotEmpty	=	-5007	#afpDirNotEmpty
afpDenyConflict	=	-5006	#afpDenyConflict
afpCantMove	=	-5005	#afpCantMove
afpBitmapErr	=	-5004	#afpBitmapErr
afpBadVersNum	=	-5003	#afpBadVersNum
afpBadUAM	=	-5002	#afpBadUAM
afpAuthContinue	=	-5001	#afpAuthContinue
afpAccessDenied	=	-5000	#afpAccessDenied
noHelpForItem	=	-4009	#noHelpForItem
badProfileError	=	-4008	#badProfileError
colorSyncNotInstalled	=	-4007	#colorSyncNotInstalled
pickerCantLive	=	-4006	#pickerCantLive
cantLoadPackage	=	-4005	#cantLoadPackage
cantCreatePickerWindow	=	-4004	#cantCreatePickerWindow
cantLoadPicker	=	-4003	#cantLoadPicker
pickerResourceError	=	-4002	#pickerResourceError
requiredFlagsDontMatch	=	-4001	#requiredFlagsDontMatch
firstPickerError	=	-4000	#firstPickerError
sktClosedErr	=	-3109	#sktClosedErr
recNotFnd	=	-3108	#recNotFnd
atpBadRsp	=	-3107	#atpBadRsp
atpLenErr	=	-3106	#atpLenErr
readQErr	=	-3105	#readQErr
extractErr	=	-3104	#extractErr
ckSumErr	=	-3103	#ckSumErr
noMPPErr	=	-3102	#noMPPErr
buf2SmallErr	=	-3101	#buf2SmallErr
noPrefAppErr	=	-3032	#noPrefAppErr
badTranslationSpecErr	=	-3031	#badTranslationSpecErr
noTranslationPathErr	=	-3030	#noTranslationPathErr
couldNotParseSourceFileErr	=	-3026	#Source document does not contain source type
invalidTranslationPathErr	=	-3025	#Source type to destination type not a valid path
componentDontRegister	=	-3003	#componentDontRegister
componentNotCaptured	=	-3002	#componentNotCaptured
validInstancesExist	=	-3001	#validInstancesExist
invalidComponentID	=	-3000	#invalidComponentID
cfragLastErrCode	=	-2899	#The last value in the range of CFM errors.
cfragAbortClosureErr	=	-2830	#Used by notification handlers to abort a closure.
cfragClosureIDErr	=	-2829	#The closure ID was not valid.
cfragContainerIDErr	=	-2828	#The fragment container ID was not valid.
cfragNoRegistrationErr	=	-2827	#The registration name was not found.
cfragNotClosureErr	=	-2826	#The closure ID was actually a connection ID.
cfragFileSizeErr	=	-2825	#A file was too large to be mapped.
cfragFragmentUsageErr	=	-2824	#A semantic error in usage of the fragment.
cfragArchitectureErr	=	-2823	#A fragment has an unacceptable architecture.
cfragNoApplicationErr	=	-2822	#No application member found in the cfrg resource.
cfragInitFunctionErr	=	-2821	#A fragment's initialization routine returned an error.
cfragFragmentCorruptErr	=	-2820	#A fragment's container was corrupt (known format).
cfragCFMInternalErr	=	-2819	#An internal inconstistancy has been detected.
cfragCFMStartupErr	=	-2818	#Internal error during CFM initialization.
cfragLibConnErr	=	-2817	#
cfragInitAtBootErr	=	-2816	#A boot library has an initialization function.  (System 7 only)
cfragInitLoopErr	=	-2815	#Circularity in required initialization order.
cfragImportTooNewErr	=	-2814	#An import library was too new for a client.
cfragImportTooOldErr	=	-2813	#An import library was too old for a client.
cfragInitOrderErr	=	-2812	#
cfragNoIDsErr	=	-2811	#No more CFM IDs for contexts, connections, etc.
cfragNoClientMemErr	=	-2810	#Out of memory for fragment mapping or section instances.
cfragNoPrivateMemErr	=	-2809	#Out of memory for internal bookkeeping.
cfragNoPositionErr	=	-2808	#The registration insertion point was not found.
cfragUnresolvedErr	=	-2807	#A fragment had "hard" unresolved imports.
cfragFragmentFormatErr	=	-2806	#A fragment's container format is unknown.
cfragDupRegistrationErr	=	-2805	#The registration name was already in use.
cfragNoLibraryErr	=	-2804	#The named library was not found.
cfragNoSectionErr	=	-2803	#The specified section was not found.
cfragNoSymbolErr	=	-2802	#The specified symbol was not found.
cfragConnectionIDErr	=	-2801	#The connection ID was not valid.
cfragFirstErrCode	=	-2800	#The first value in the range of CFM errors.
errASInconsistentNames	=	-2780	#English errors:
errASNoResultReturned	=	-2763	#The range -2780 thru -2799 is reserved for dialect specific error codes. (Error codes from different dialects may overlap.)
errASParameterNotForEvent	=	-2762	#errASParameterNotForEvent
errASIllegalFormalParameter	=	-2761	#errASIllegalFormalParameter
errASTerminologyNestingTooDeep	=	-2760	#errASTerminologyNestingTooDeep
errASCantCompareMoreThan32k	=	-2721	#Parser/Compiler errors:
errASCantConsiderAndIgnore	=	-2720	#errASCantConsiderAndIgnore
nrTransactionAborted	=	-2556	#transaction was aborted
nrExitedIteratorScope	=	-2555	#outer scope of iterator was exited
nrIterationDone	=	-2554	#iteration operation is done
nrPropertyAlreadyExists	=	-2553	#property already exists
nrInvalidEntryIterationOp	=	-2552	#invalid entry iteration operation
nrPathBufferTooSmall	=	-2551	#buffer for path is too small
nrPathNotFound	=	-2550	#a path component lookup failed
nrResultCodeBase	=	-2549	#nrResultCodeBase
nrOverrunErr	=	-2548	#nrOverrunErr
nrNotModifiedErr	=	-2547	#nrNotModifiedErr
nrTypeMismatchErr	=	-2546	#nrTypeMismatchErr
nrPowerSwitchAbortErr	=	-2545	#nrPowerSwitchAbortErr
nrPowerErr	=	-2544	#nrPowerErr
nrDataTruncatedErr	=	-2543	#nrDataTruncatedErr
nrNotSlotDeviceErr	=	-2542	#nrNotSlotDeviceErr
nrNameErr	=	-2541	#nrNameErr
nrNotCreatedErr	=	-2540	#nrNotCreatedErr
nrNotFoundErr	=	-2539	#nrNotFoundErr
nrInvalidNodeErr	=	-2538	#nrInvalidNodeErr
nrNotEnoughMemoryErr	=	-2537	#nrNotEnoughMemoryErr
nrLockedErr	=	-2536	#nrLockedErr
mmInternalError	=	-2526	#mmInternalError
tsmNoStem	=	-2523	#No stem exists for the token
tsmNoMoreTokens	=	-2522	#No more tokens are available for the source text
tsmNoHandler	=	-2521	#No Callback Handler exists for callback
tsmInvalidContext	=	-2520	#Invalid TSMContext specified in call
tsmUnknownErr	=	-2519	#any other errors
tsmUnsupportedTypeErr	=	-2518	#unSupported interface type error
tsmScriptHasNoIMErr	=	-2517	#script has no imput method or is using old IM
tsmInputMethodIsOldErr	=	-2516	#returned by GetDefaultInputMethod
tsmComponentAlreadyOpenErr	=	-2515	#text service already opened for the document
tsmTSNotOpenErr	=	-2514	#text service is not open
tsmTSHasNoMenuErr	=	-2513	#the text service has no menu
tsmUseInputWindowErr	=	-2512	#not TSM aware because we are using input window
tsmDocumentOpenErr	=	-2511	#there are open documents
tsmTextServiceNotFoundErr	=	-2510	#no text service found
tsmCantOpenComponentErr	=	-2509	#can¹t open the component
tsmNoOpenTSErr	=	-2508	#no open text service
tsmDocNotActiveErr	=	-2507	#document is NOT active
tsmTSMDocBusyErr	=	-2506	#document is still active
tsmInvalidDocIDErr	=	-2505	#invalid TSM documentation id
tsmNeverRegisteredErr	=	-2504	#app never registered error (not TSM aware)
tsmAlreadyRegisteredErr	=	-2503	#want to register again error
tsmNotAnAppErr	=	-2502	#not an application error
tsmInputMethodNotFoundErr	=	-2501	#tsmInputMethodNotFoundErr
tsmUnsupScriptLanguageErr	=	-2500	#tsmUnsupScriptLanguageErr
kernelUnrecoverableErr	=	-2499	#kernelUnrecoverableErr
kernelReturnValueErr	=	-2422	#kernelReturnValueErr
kernelAlreadyFreeErr	=	-2421	#kernelAlreadyFreeErr
kernelIDErr	=	-2419	#kernelIDErr
kernelExceptionErr	=	-2418	#kernelExceptionErr
kernelTerminatedErr	=	-2417	#kernelTerminatedErr
kernelInUseErr	=	-2416	#kernelInUseErr
kernelTimeoutErr	=	-2415	#kernelTimeoutErr
kernelAsyncReceiveLimitErr	=	-2414	#kernelAsyncReceiveLimitErr
kernelAsyncSendLimitErr	=	-2413	#kernelAsyncSendLimitErr
kernelAttributeErr	=	-2412	#kernelAttributeErr
kernelExecutionLevelErr	=	-2411	#kernelExecutionLevelErr
kernelDeletePermissionErr	=	-2410	#kernelDeletePermissionErr
kernelExecutePermissionErr	=	-2409	#kernelExecutePermissionErr
kernelReadPermissionErr	=	-2408	#kernelReadPermissionErr
kernelWritePermissionErr	=	-2407	#kernelWritePermissionErr
kernelObjectExistsErr	=	-2406	#kernelObjectExistsErr
kernelUnsupportedErr	=	-2405	#kernelUnsupportedErr
kernelPrivilegeErr	=	-2404	#kernelPrivilegeErr
kernelOptionsErr	=	-2403	#kernelOptionsErr
kernelCanceledErr	=	-2402	#kernelCanceledErr
kernelIncompleteErr	=	-2401	#kernelIncompleteErr
badCallOrderErr	=	-2209	#Usually due to a status call being called prior to being setup first
noDMAErr	=	-2208	#Can¹t do DMA digitizing (i.e. can't go to requested dest
badDepthErr	=	-2207	#Can¹t digitize into this depth
notExactSizeErr	=	-2206	#Can¹t do exact size requested
noMoreKeyColorsErr	=	-2205	#all key indexes in use
notExactMatrixErr	=	-2204	#warning of bad matrix, digitizer did its best
matrixErr	=	-2203	#bad matrix, digitizer did nothing
qtParamErr	=	-2202	#bad input parameter (out of range, etc)
digiUnimpErr	=	-2201	#feature unimplemented
invalidAtomTypeErr	=	-2108	#invalidAtomTypeErr
invalidAtomContainerErr	=	-2107	#invalidAtomContainerErr
invalidAtomErr	=	-2106	#invalidAtomErr
duplicateAtomTypeAndIDErr	=	-2105	#duplicateAtomTypeAndIDErr
atomIndexInvalidErr	=	-2104	#atomIndexInvalidErr
atomsNotOfSameTypeErr	=	-2103	#atomsNotOfSameTypeErr
notLeafAtomErr	=	-2102	#notLeafAtomErr
cannotFindAtomErr	=	-2101	#cannotFindAtomErr
invalidImageIndexErr	=	-2068	#invalidImageIndexErr
invalidSpriteIndexErr	=	-2067	#invalidSpriteIndexErr
gWorldsNotSameDepthAndSizeErr	=	-2066	#gWorldsNotSameDepthAndSizeErr
invalidSpritePropertyErr	=	-2065	#invalidSpritePropertyErr
invalidSpriteWorldPropertyErr	=	-2064	#invalidSpriteWorldPropertyErr
movieTextNotFoundErr	=	-2062	#movieTextNotFoundErr
samplesAlreadyInMediaErr	=	-2059	#samplesAlreadyInMediaErr
auxiliaryExportDataUnavailable	=	-2058	#auxiliaryExportDataUnavailable
unsupportedAuxiliaryImportData	=	-2057	#unsupportedAuxiliaryImportData
soundSupportNotAvailableErr	=	-2056	#QT for Windows error
noSoundTrackInMovieErr	=	-2055	#QT for Windows error
noVideoTrackInMovieErr	=	-2054	#QT for Windows error
featureUnsupported	=	-2053	#featureUnsupported
couldNotUseAnExistingSample	=	-2052	#couldNotUseAnExistingSample
noDefaultDataRef	=	-2051	#noDefaultDataRef
badDataRefIndex	=	-2050	#badDataRefIndex
invalidDataRefContainer	=	-2049	#invalidDataRefContainer
noMovieFound	=	-2048	#noMovieFound
dataNoDataRef	=	-2047	#dataNoDataRef
endOfDataReached	=	-2046	#endOfDataReached
dataAlreadyClosed	=	-2045	#dataAlreadyClosed
dataAlreadyOpenForWrite	=	-2044	#dataAlreadyOpenForWrite
dataNotOpenForWrite	=	-2043	#dataNotOpenForWrite
dataNotOpenForRead	=	-2042	#dataNotOpenForRead
invalidSampleDescription	=	-2041	#invalidSampleDescription
invalidChunkCache	=	-2040	#invalidChunkCache
invalidSampleDescIndex	=	-2039	#invalidSampleDescIndex
invalidChunkNum	=	-2038	#invalidChunkNum
invalidSampleNum	=	-2037	#invalidSampleNum
invalidRect	=	-2036	#invalidRect
cantEnableTrack	=	-2035	#cantEnableTrack
internalQuickTimeError	=	-2034	#internalQuickTimeError
badEditIndex	=	-2033	#badEditIndex
timeNotInMedia	=	-2032	#timeNotInMedia
timeNotInTrack	=	-2031	#timeNotInTrack
trackNotInMovie	=	-2030	#trackNotInMovie
trackIDNotFound	=	-2029	#trackIDNotFound
badTrackIndex	=	-2028	#badTrackIndex
maxSizeToGrowTooSmall	=	-2027	#maxSizeToGrowTooSmall
userDataItemNotFound	=	-2026	#userDataItemNotFound
staleEditState	=	-2025	#staleEditState
nonMatchingEditState	=	-2024	#nonMatchingEditState
invalidEditState	=	-2023	#invalidEditState
cantCreateSingleForkFile	=	-2022	#happens when file already exists
wfFileNotFound	=	-2021	#wfFileNotFound
movieToolboxUninitialized	=	-2020	#movieToolboxUninitialized
progressProcAborted	=	-2019	#progressProcAborted
mediaTypesDontMatch	=	-2018	#mediaTypesDontMatch
badEditList	=	-2017	#badEditList
cantPutPublicMovieAtom	=	-2016	#cantPutPublicMovieAtom
invalidTime	=	-2015	#invalidTime
invalidDuration	=	-2014	#invalidDuration
invalidHandler	=	-2013	#invalidHandler
invalidDataRef	=	-2012	#invalidDataRef
invalidSampleTable	=	-2011	#invalidSampleTable
invalidMovie	=	-2010	#invalidMovie
invalidTrack	=	-2009	#invalidTrack
invalidMedia	=	-2008	#invalidMedia
noDataHandler	=	-2007	#noDataHandler
noMediaHandler	=	-2006	#noMediaHandler
badComponentType	=	-2005	#badComponentType
cantOpenHandler	=	-2004	#cantOpenHandler
cantFindHandler	=	-2003	#cantFindHandler
badPublicMovieAtom	=	-2002	#badPublicMovieAtom
badImageDescription	=	-2001	#badImageDescription
couldNotResolveDataRef	=	-2000	#couldNotResolveDataRef
badImageErr	=	-1861	#bad translucent image PixMap
badImageRgnErr	=	-1860	#bad translucent image region
noSuitableDisplaysErr	=	-1859	#no displays support translucency
unsupportedForPlatformErr	=	-1858	#call is for PowerPC only
dragNotAcceptedErr	=	-1857	#drag was not accepted by receiver
handlerNotFoundErr	=	-1856	#handler not found
duplicateHandlerErr	=	-1855	#handler already exists
cantGetFlavorErr	=	-1854	#error while trying to get flavor data
duplicateFlavorErr	=	-1853	#flavor type already exists
badDragFlavorErr	=	-1852	#unknown flavor type
badDragItemErr	=	-1851	#unknown drag item reference
badDragRefErr	=	-1850	#unknown drag reference
errEndOfBody	=	-1813	#errEndOfBody
errEndOfDocument	=	-1812	#errEndOfDocument
errTopOfBody	=	-1811	#errTopOfBody
errTopOfDocument	=	-1810	#errTopOfDocument
errOffsetIsOutsideOfView	=	-1801	#errOffsetIsOutsideOfView
errOffsetInvalid	=	-1800	#errOffsetInvalid
errOSACantOpenComponent	=	-1762	#Can't connect to scripting system with that ID
errOSAComponentMismatch	=	-1761	#Parameters are from 2 different components
errOSADataFormatTooNew	=	-1759	#errOSADataFormatTooNew
errOSADataFormatObsolete	=	-1758	#errOSADataFormatObsolete
errOSANoSuchDialect	=	-1757	#errOSANoSuchDialect
errOSASourceNotAvailable	=	-1756	#errOSASourceNotAvailable
errOSABadSelector	=	-1754	#errOSABadSelector
errOSAScriptError	=	-1753	#errOSAScriptError
errOSABadStorageType	=	-1752	#errOSABadStorageType
errOSAInvalidID	=	-1751	#errOSAInvalidID
errOSASystemError	=	-1750	#errOSASystemError
errAEDescIsNull	=	-1739	#attempting to perform an invalid operation on a null descriptor
errAEStreamAlreadyConverted	=	-1738	#attempt to convert a stream that has already been converted
errAEStreamBadNesting	=	-1737	#nesting violation while streaming
errAEDuplicateHandler	=	-1736	#attempt to install handler in table for identical class and id (1.1 or greater)
errAEEventFiltered	=	-1735	#event has been filtered, and should not be propogated (1.1 or greater)
errAEReceiveEscapeCurrent	=	-1734	#break out of only lowest level of AEReceive (1.1 or greater)
errAEReceiveTerminate	=	-1733	#break out of all levels of AEReceive to the topmost (1.1 or greater)
errAERecordingIsAlreadyOn	=	-1732	#available only in version 1.0.1 or greater
errAEUnknownObjectType	=	-1731	#available only in version 1.0.1 or greater
errAEEmptyListContainer	=	-1730	#Attempt to pass empty list as container to accessor
errAENegativeCount	=	-1729	#CountProc returned negative value
errAENoSuchObject	=	-1728	#e.g.,: specifier asked for the 3rd, but there are only 2. Basically, this indicates a run-time resolution error.
errAENotAnObjSpec	=	-1727	#Param to AEResolve not of type 'obj '
errAEBadTestKey	=	-1726	#Test is neither typeLogicalDescriptor nor typeCompDescriptor
errAENoSuchLogical	=	-1725	#Something other than AND, OR, or NOT
errAEAccessorNotFound	=	-1723	#Accessor proc matching wantClass and containerType or wildcards not found
errAEWrongNumberArgs	=	-1721	#Logical op kAENOT used with other than 1 term
errAEImpossibleRange	=	-1720	#A range like 3rd to 2nd, or 1st to all.
errAEIllegalIndex	=	-1719	#index is out of range in a put operation
errAEReplyNotArrived	=	-1718	#the contents of the reply you are accessing have not arrived yet
errAEHandlerNotFound	=	-1717	#no handler in the dispatch tables fits the parameters to AEGetEventHandler or AEGetCoercionHandler
errAEUnknownAddressType	=	-1716	#the target address type is not known
errAEParamMissed	=	-1715	#a required parameter was not accessed
errAENotASpecialFunction	=	-1714	#there is no special function for/with this keyword
errAENoUserInteraction	=	-1713	#no user interaction is allowed
errAETimeout	=	-1712	#the AppleEvent timed out
errAEWaitCanceled	=	-1711	#in AESend, the user cancelled out of wait loop for reply or receipt
errAEUnknownSendMode	=	-1710	#mode wasn't NoReply, WaitReply, or QueueReply or Interaction level is unknown
errAEReplyNotValid	=	-1709	#AEResetTimer was passed an invalid reply parameter
errAEEventNotHandled	=	-1708	#the AppleEvent was not handled by any handler
errAENotAppleEvent	=	-1707	#the event is not in AppleEvent format
errAENewerVersion	=	-1706	#need newer version of the AppleEvent manager
errAEBadListItem	=	-1705	#the specified list item does not exist
errAENotAEDesc	=	-1704	#errAENotAEDesc
errAEWrongDataType	=	-1703	#errAEWrongDataType
errAECorruptData	=	-1702	#errAECorruptData
errAEDescNotFound	=	-1701	#errAEDescNotFound
errAECoercionFail	=	-1700	#bad parameter data or unable to coerce the data supplied
volVMBusyErr	=	-1311	#can't eject because volume is in use by VM
fsDataTooBigErr	=	-1310	#file or volume is too big for system
fileBoundsErr	=	-1309	#file's EOF, offset, mark or size is too big
notARemountErr	=	-1308	#when _Mount allows only remounts and doesn't get one
badFidErr	=	-1307	#file id is dangling or doesn't match with the file number
sameFileErr	=	-1306	#can't exchange a file with itself
desktopDamagedErr	=	-1305	#desktop database files are corrupted
catChangedErr	=	-1304	#the catalog has been modified
diffVolErr	=	-1303	#files on different volumes
notAFileErr	=	-1302	#directory specified
fidExists	=	-1301	#file id already exists
fidNotFound	=	-1300	#no file thread exists.
errRefNum	=	-1280	#bad connection refNum
errAborted	=	-1279	#control call was aborted
errState	=	-1278	#bad connection state for this operation
errOpening	=	-1277	#open connection request failed
errAttention	=	-1276	#attention message too long
errFwdReset	=	-1275	#read terminated by forward reset
errDSPQueueSize	=	-1274	#DSP Read/Write Queue Too small
errOpenDenied	=	-1273	#open connection request was denied
reqAborted	=	-1105	#reqAborted
noDataArea	=	-1104	#noDataArea
noSendResp	=	-1103	#noSendResp
cbNotFound	=	-1102	#cbNotFound
noRelErr	=	-1101	#noRelErr
badBuffNum	=	-1100	#badBuffNum
badATPSkt	=	-1099	#badATPSkt
tooManySkts	=	-1098	#tooManySkts
tooManyReqs	=	-1097	#tooManyReqs
reqFailed	=	-1096	#reqFailed
aspNoAck	=	-1075	#No ack on attention request (server err)
aspTooMany	=	-1074	#Too many clients (server error)
aspSizeErr	=	-1073	#Command block too big
aspSessClosed	=	-1072	#Session closed
aspServerBusy	=	-1071	#Server cannot open another session
aspParamErr	=	-1070	#Parameter error
aspNoServers	=	-1069	#No servers at that address
aspNoMoreSess	=	-1068	#No more sessions on server
aspBufTooSmall	=	-1067	#Buffer too small
aspBadVersNum	=	-1066	#Server cannot support this ASP version
nbpNISErr	=	-1029	#Error trying to open the NIS
nbpNotFound	=	-1028	#Name not found on remove
nbpDuplicate	=	-1027	#Duplicate name exists already
nbpConfDiff	=	-1026	#Name confirmed at different socket
nbpNoConfirm	=	-1025	#nbpNoConfirm
nbpBuffOvr	=	-1024	#Buffer overflow in LookupName
noMaskFoundErr	=	-1000	#Icon Utilties Error
guestNotAllowedErr	=	-932	#destination port requires authentication
badLocNameErr	=	-931	#location name malformed
badServiceMethodErr	=	-930	#illegal service type, or not supported
noUserRecErr	=	-928	#Invalid user reference number
authFailErr	=	-927	#unable to authenticate user at destination
noInformErr	=	-926	#PPCStart failed because destination did not have inform pending
networkErr	=	-925	#An error has occured in the network, not too likely
noUserRefErr	=	-924	#unable to create a new userRefNum
notLoggedInErr	=	-923	#The default userRefNum does not yet exist
noDefaultUserErr	=	-922	#user hasn't typed in owners name in Network Setup Control Pannel
badPortNameErr	=	-919	#PPCPortRec malformed
sessClosedErr	=	-917	#session was closed
portClosedErr	=	-916	#port was closed
noResponseErr	=	-915	#unable to contact destination
noToolboxNameErr	=	-914	#A system resource is missing, not too likely
noMachineNameErr	=	-913	#user hasn't named his Macintosh in the Network Setup Control Panel
userRejectErr	=	-912	#Destination rejected the session request
noUserNameErr	=	-911	#user name unknown on destination machine
portNameExistsErr	=	-910	#port is already open (perhaps in another app)
badReqErr	=	-909	#bad parameter or invalid state for operation
noSessionErr	=	-908	#Invalid session reference number
sessTableErr	=	-907	#Out of session tables, try again later
destPortErr	=	-906	#Port does not exist at destination
localOnlyErr	=	-905	#Network activity is currently disabled
noGlobalsErr	=	-904	#The system is hosed, better re-boot
noPortErr	=	-903	#Unable to open port or bad portRefNum
nameTypeErr	=	-902	#Invalid or inappropriate locationKindSelector in locationName
notInitErr	=	-900	#PPCToolBox not initialized
hmCloseViewActive	=	-863	#Returned from HMRemoveBalloon if CloseView was active
hmNoBalloonUp	=	-862	#Returned from HMRemoveBalloon if no balloon was visible when call was made
hmOperationUnsupported	=	-861	#Returned from HMShowBalloon call if bad method passed to routine
hmUnknownHelpType	=	-859	#Returned if help msg record contained a bad type
hmWrongVersion	=	-858	#Returned if help mgr resource was the wrong version
hmSkippedBalloon	=	-857	#Returned from calls if helpmsg specified a skip balloon
hmHelpManagerNotInited	=	-855	#Returned from HMGetHelpMenuHandle if help menu not setup
hmSameAsLastBalloon	=	-854	#Returned from HMShowMenuBalloon if menu & item is same as last time
hmBalloonAborted	=	-853	#Returned if mouse was moving or mouse wasn't in window port rect
hmHelpDisabled	=	-850	#Show Balloons mode was off, call to routine ignored
rcDBPackNotInited	=	-813	#attempt to call other routine before InitDBPack
rcDBWrongVersion	=	-812	#incompatible versions
rcDBNoHandler	=	-811	#no app handler for specified data type
rcDBBadAsyncPB	=	-810	#tried to kill a bad pb
rcDBAsyncNotSupp	=	-809	#ddev does not support async calls
rcDBBadDDEV	=	-808	#bad ddev specified on DBInit
rcDBBadSessNum	=	-807	#bad session number for DBGetConnInfo
rcDBBadSessID	=	-806	#rcDBBadSessID
rcDBExec	=	-805	#rcDBExec
rcDBBreak	=	-804	#rcDBBreak
rcDBBadType	=	-803	#rcDBBadType
rcDBError	=	-802	#rcDBError
rcDBValue	=	-801	#rcDBValue
rcDBNull	=	-800	#rcDBNull
noMMUErr	=	-626	#no MMU present
cannotDeferErr	=	-625	#unable to defer additional functions
interruptsMaskedErr	=	-624	#don¹t call with interrupts masked
notLockedErr	=	-623	#specified range of memory is not locked
cannotMakeContiguousErr	=	-622	#cannot make specified range contiguous
notHeldErr	=	-621	#specified range of memory is not held
notEnoughMemoryErr	=	-620	#insufficient physical memory
threadProtocolErr	=	-619	#threadProtocolErr
threadNotFoundErr	=	-618	#threadNotFoundErr
threadTooManyReqsErr	=	-617	#threadTooManyReqsErr
noUserInteractionAllowed	=	-610	#no user interaction allowed
connectionInvalid	=	-609	#connectionInvalid
noOutstandingHLE	=	-608	#noOutstandingHLE
bufferIsSmall	=	-607	#error returns from Post and Accept
appIsDaemon	=	-606	#app is BG-only, and launch flags disallow this
appMemFullErr	=	-605	#application SIZE not big enough for launch
hardwareConfigErr	=	-604	#hardware configuration not correct for call
protocolErr	=	-603	#app made module calls in improper order
appModeErr	=	-602	#memory mode is 32-bit, but app not 32-bit clean
memFragErr	=	-601	#not enough room to launch app w/special requirements
procNotFound	=	-600	#no eligible process with specified descriptor
hwParamErr	=	-502	#bad selector for _HWPriv
teScrapSizeErr	=	-501	#scrap item too big for text edit record
rgnTooBigErr	=	-500	#rgnTooBigErr
exUserBreak	=	-492	#user debugger break; execute debugger commands on stack
strUserBreak	=	-491	#user debugger break; display string on stack
userBreak	=	-490	#user debugger break
notThePublisherWrn	=	-463	#not the first registered publisher for that container
containerAlreadyOpenWrn	=	-462	#container already opened by this section
containerNotFoundWrn	=	-461	#could not find editionContainer at this time
multiplePublisherWrn	=	-460	#A Publisher is already registered for that container
badSubPartErr	=	-454	#can not use sub parts in this release
badEditionFileErr	=	-453	#edition file is corrupt
notRegisteredSectionErr	=	-452	#not a registered SectionRecord
badSectionErr	=	-451	#not a valid SectionRecord
editionMgrInitErr	=	-450	#edition manager not inited by this app
btKeyAttrErr	=	-417	#There is no such a key attribute.
btKeyLenErr	=	-416	#Maximum key length is too long or equal to zero.
btRecNotFnd	=	-415	#Record cannot be found.
btDupRecErr	=	-414	#Record already exists.
btNoSpace	=	-413	#Can't allocate disk space.
notBTree	=	-410	#The file is not a dictionary.
gcrOnMFMErr	=	-400	#gcr format on high density media error
slotNumErr	=	-360	#invalid slot # error
smRecNotFnd	=	-351	#Record not found in the SRT.
smSRTOvrFlErr	=	-350	#SRT over flow.
smNoGoodOpens	=	-349	#No opens were successfull in the loop.
smOffsetErr	=	-348	#Offset was too big (temporary error
smByteLanesErr	=	-347	#NumByteLanes was determined to be zero.
smBadsPtrErr	=	-346	#Bad pointer was passed to sCalcsPointer
smsGetDrvrErr	=	-345	#Error occurred during _sGetDriver.
smNoMoresRsrcs	=	-344	#No more sResources
smDisDrvrNamErr	=	-343	#Error occured during _sDisDrvrName.
smGetDrvrNamErr	=	-342	#Error occured during _sGetDrvrName.
smCkStatusErr	=	-341	#Status of slot = fail.
smBlkMoveErr	=	-340	#_BlockMove error
smNewPErr	=	-339	#_NewPtr error
smSelOOBErr	=	-338	#Selector out of bounds error
smSlotOOBErr	=	-337	#Slot out of bounds error
smNilsBlockErr	=	-336	#Nil sBlock error (Dont allocate and try to use a nil sBlock)
smsPointerNil	=	-335	#LPointer is nil From sOffsetData. If this error occurs; check sInfo rec for more information.
smCPUErr	=	-334	#Code revision is wrong
smCodeRevErr	=	-333	#Code revision is wrong
smReservedErr	=	-332	#Reserved field not zero
smBadsList	=	-331	#Bad sList: Id1 < Id2 < Id3 ...format is not followed.
smBadRefId	=	-330	#Reference Id not found in List
smBusErrTO	=	-320	#BusError time out.
smBadBoardId	=	-319	#BoardId was wrong; re-init the PRAM record.
smReservedSlot	=	-318	#slot is reserved, VM should not use this address space.
smInitTblVErr	=	-317	#An error occured while trying to initialize the Slot Resource Table.
smInitStatVErr	=	-316	#The InitStatusV field was negative after primary or secondary init.
smNoBoardId	=	-315	#No Board Id.
smGetPRErr	=	-314	#Error occured during _sGetPRAMRec (See SIMStatus).
smNoBoardSRsrc	=	-313	#No Board sResource.
smDisposePErr	=	-312	#_DisposePointer error
smFHBlkDispErr	=	-311	#Error occured during _sDisposePtr (Dispose of FHeader block).
smFHBlockRdErr	=	-310	#Error occured during _sGetFHeader.
smBLFieldBad	=	-309	#ByteLanes field was bad.
smUnExBusErr	=	-308	#Unexpected BusError
smResrvErr	=	-307	#Fatal reserved error. Resreved field <> 0.
smNosInfoArray	=	-306	#No sInfoArray. Memory Mgr error.
smDisabledSlot	=	-305	#This slot is disabled (-305 use to be smLWTstBad)
smNoDir	=	-304	#Directory offset is Nil
smRevisionErr	=	-303	#Wrong revison level
smFormatErr	=	-302	#FHeader Format is not Apple's
smCRCFail	=	-301	#CRC check failed for declaration data
smEmptySlot	=	-300	#No card in slot
nmTypErr	=	-299	#wrong queue type
smPriInitErr	=	-293	#Error; Cards could not be initialized.
smPRAMInitErr	=	-292	#Error; Slot Resource Table could not be initialized.
smSRTInitErr	=	-291	#Error; Slot Resource Table could not be initialized.
smSDMInitErr	=	-290	#Error; SDM could not be initialized.
midiInvalidCmdErr	=	-261	#command not supported for port type
midiDupIDErr	=	-260	#duplicate client ID
midiNameLenErr	=	-259	#name supplied is longer than 31 characters
midiWriteErr	=	-258	#MIDIWritePacket couldn't write to all connected ports
midiNoConErr	=	-257	#no connection exists between specified ports
midiVConnectRmvd	=	-256	#pending virtual connection removed
midiVConnectMade	=	-255	#pending virtual connection resolved
midiVConnectErr	=	-254	#pending virtual connection created
midiTooManyConsErr	=	-253	#too many connections made
midiTooManyPortsErr	=	-252	#too many ports already installed in the system
midiNoPortErr	=	-251	#no port with that ID found
midiNoClientErr	=	-250	#no client with that ID found
badInputText	=	-247	#badInputText
badDictFormat	=	-246	#badDictFormat
incompatibleVoice	=	-245	#incompatibleVoice
voiceNotFound	=	-244	#voiceNotFound
bufTooSmall	=	-243	#bufTooSmall
synthNotReady	=	-242	#synthNotReady
synthOpenFailed	=	-241	#synthOpenFailed
noSynthFound	=	-240	#noSynthFound
siUnknownQuality	=	-232	#invalid quality selector (returned by driver)
siUnknownInfoType	=	-231	#invalid info type selector (returned by driver)
siInputDeviceErr	=	-230	#input device hardware failure
siBadRefNum	=	-229	#invalid input device reference number
siBadDeviceName	=	-228	#input device could not be opened
siDeviceBusyErr	=	-227	#input device already in use
siInvalidSampleSize	=	-226	#invalid sample size
siInvalidSampleRate	=	-225	#invalid sample rate
siHardDriveTooSlow	=	-224	#hard drive too slow to record to disk
siInvalidCompression	=	-223	#invalid compression type
siNoBufferSpecified	=	-222	#returned by synchronous SPBRecord if nil buffer passed
siBadSoundInDevice	=	-221	#invalid index passed to SoundInGetIndexedDevice
siNoSoundInHardware	=	-220	#no Sound Input hardware
noMoreRealTime	=	-212	#not enough CPU cycles left to add another task
channelNotBusy	=	-211	#channelNotBusy
buffersTooSmall	=	-210	#can not operate in the memory allowed
channelBusy	=	-209	#the Channel is being used for a PFD already
badFileFormat	=	-208	#was not type AIFF or was of bad format,corrupt
notEnoughBufferSpace	=	-207	#could not allocate enough memory
badFormat	=	-206	#Sound Manager Error Returns
badChannel	=	-205	#Sound Manager Error Returns
resProblem	=	-204	#Sound Manager Error Returns
queueFull	=	-203	#Sound Manager Error Returns
notEnoughHardwareErr	=	-201	#Sound Manager Error Returns
noHardwareErr	=	-200	#Sound Manager Error Returns
mapReadErr	=	-199	#map inconsistent with operation
resAttrErr	=	-198	#attribute inconsistent with operation
rmvRefFailed	=	-197	#RmveReference failed
rmvResFailed	=	-196	#RmveResource failed
addRefFailed	=	-195	#AddReference failed
addResFailed	=	-194	#AddResource failed
resFNotFound	=	-193	#Resource file not found
resNotFound	=	-192	#Resource not found
inputOutOfBounds	=	-190	#Offset of Count out of bounds
writingPastEnd	=	-189	#Writing past end of file
resourceInMemory	=	-188	#Resource already in memory
CantDecompress	=	-186	#resource bent ("the bends") - can't decompress a compressed resource
badExtResource	=	-185	#extended resource has a bad format.
cDepthErr	=	-157	#invalid pixel depth
cResErr	=	-156	#invalid resolution for MakeITable
cDevErr	=	-155	#invalid type of graphics device
cProtectErr	=	-154	#colorTable entry protection violation
cRangeErr	=	-153	#range error on colorTable request
cNoMemErr	=	-152	#failed to allocate memory for structure
cTempMemErr	=	-151	#failed to allocate memory for temporary structures
cMatchErr	=	-150	#Color2Index failed to find an index
insufficientStackErr	=	-149	#insufficientStackErr
pixMapTooDeepErr	=	-148	#pixMapTooDeepErr
rgnOverflowErr	=	-147	#rgnOverflowErr
noMemForPictPlaybackErr	=	-145	#noMemForPictPlaybackErr
userCanceledErr	=	-128	#userCanceledErr
hMenuFindErr	=	-127	#could not find HMenu's parent in MenuKey
mBarNFnd	=	-126	#system error code for MBDF not found
updPixMemErr	=	-125	#insufficient memory to update a pixmap
volGoneErr	=	-124	#Server volume has been disconnected.
wrgVolTypErr	=	-123	#Wrong volume type error [operation not supported for MFS]
badMovErr	=	-122	#Move into offspring error
tmwdoErr	=	-121	#No free WDCB available
dirNFErr	=	-120	#Directory not found
memLockedErr	=	-117	#trying to move a locked block (MoveHHi)
memSCErr	=	-116	#Size Check failed
memBCErr	=	-115	#Block Check failed
memPCErr	=	-114	#Pointer Check failed
memAZErr	=	-113	#Address in zone check failed
memPurErr	=	-112	#trying to purge a locked or non-purgeable block
memWZErr	=	-111	#WhichZone failed (applied to free block)
memAdrErr	=	-110	#address was odd; or out of range
nilHandleErr	=	-109	#Master Pointer was NIL in HandleZone or other
memFullErr	=	-108	#Not enough room in heap zone
noTypeErr	=	-102	#No object of that type in scrap
noScrapErr	=	-100	#No scrap exists error
memROZWarn	=	-99	#soft error in ROZ
portNotCf	=	-98	#driver Open error code (parameter RAM not configured for this connection)
portInUse	=	-97	#driver Open error code (port is in use)
portNotPwr	=	-96	#serial port not currently powered
excessCollsns	=	-95	#excessive collisions on write
lapProtErr	=	-94	#error in attaching/detaching protocol
noBridgeErr	=	-93	#no network bridge for non-local send
eLenErr	=	-92	#Length error ddpLenErr
eMultiErr	=	-91	#Multicast address error ddpSktErr
breakRecd	=	-90	#Break received (SCC)
rcvrErr	=	-89	#SCC receiver error (framing; parity; OR)
prInitErr	=	-88	#InitUtil found the parameter ram uninitialized
prWrErr	=	-87	#parameter ram written didn't read-verify
clkWrErr	=	-86	#time written did not verify
clkRdErr	=	-85	#unable to read same clock value twice
verErr	=	-84	#track failed to verify
fmt2Err	=	-83	#can't get enough sync
fmt1Err	=	-82	#can't find sector 0 after track format
sectNFErr	=	-81	#sector number never found on a track
seekErr	=	-80	#track number wrong on address mark
spdAdjErr	=	-79	#unable to correctly adjust disk speed
twoSideErr	=	-78	#tried to read 2nd side on a 1-sided drive
initIWMErr	=	-77	#unable to initialize IWM
tk0BadErr	=	-76	#track 0 detect doesn't change
cantStepErr	=	-75	#step handshake failed
wrUnderrun	=	-74	#write underrun occurred
badDBtSlp	=	-73	#bad data mark bit slip nibbles
badDCksum	=	-72	#bad data mark checksum
noDtaMkErr	=	-71	#couldn't find a data mark header
badBtSlpErr	=	-70	#bad addr mark bit slip nibbles
badCksmErr	=	-69	#addr mark checksum didn't check
dataVerErr	=	-68	#read verify compare failed
noAdrMkErr	=	-67	#couldn't find valid addr mark
noNybErr	=	-66	#couldn't find 5 nybbles in 200 tries
offLinErr	=	-65	#r/w requested for an off-line drive
fontDecError	=	-64	#error during font declaration
wrPermErr	=	-61	#write permissions error
badMDBErr	=	-60	#bad master directory block
fsRnErr	=	-59	#file system internal error:during rename the old entry was deleted but could not be restored.
extFSErr	=	-58	#volume in question belongs to an external fs
noMacDskErr	=	-57	#not a mac diskette (sig bytes are wrong)
nsDrvErr	=	-56	#no such drive (tried to mount a bad drive num)
volOnLinErr	=	-55	#drive volume already on-line at MountVol
permErr	=	-54	#permissions error (on file open)
volOffLinErr	=	-53	#volume not on line error (was Ejected)
gfpErr	=	-52	#get file position error
rfNumErr	=	-51	#refnum error
paramErr	=	-50	#error in user parameter list
opWrErr	=	-49	#file already open with with write permission
dupFNErr	=	-48	#duplicate filename (rename)
fBsyErr	=	-47	#File is busy (delete)
vLckdErr	=	-46	#volume is locked
fLckdErr	=	-45	#file is locked
wPrErr	=	-44	#diskette is write protected.
fnfErr	=	-43	#File not found
tmfoErr	=	-42	#too many files open
mFulErr	=	-41	#memory full (open) or file won't fit (load)
posErr	=	-40	#tried to position to before start of file (r/w)
eofErr	=	-39	#End of file
fnOpnErr	=	-38	#File not open
bdNamErr	=	-37	#there may be no bad names in the final system!
ioErr	=	-36	#I/O error (bummers)
nsvErr	=	-35	#no such volume
dskFulErr	=	-34	#disk full
dirFulErr	=	-33	#Directory full
dceExtErr	=	-30	#dce extension error
unitTblFullErr	=	-29	#unit table has no more entries
notOpenErr	=	-28	#Couldn't rd/wr/ctl/sts cause driver not opened
iIOAbortErr	=	-27	#IO abort error (Printing Manager)
dInstErr	=	-26	#DrvrInstall couldn't find driver in resources
dRemovErr	=	-25	#tried to remove an open driver
closErr	=	-24	#I/O System Errors
openErr	=	-23	#I/O System Errors
unitEmptyErr	=	-22	#I/O System Errors
badUnitErr	=	-21	#I/O System Errors
writErr	=	-20	#I/O System Errors
readErr	=	-19	#I/O System Errors
statusErr	=	-18	#I/O System Errors
controlErr	=	-17	#I/O System Errors
dsExtensionsDisabled	=	-13	#say ³Extensions Disabled²
dsHD20Installed	=	-12	#say ³HD20 Startup²
dsDisassemblerInstalled	=	-11	#say ³Disassembler Installed²
dsMacsBugInstalled	=	-10	#say ³MacsBug Installed²
seNoDB	=	-8	#no debugger installed to handle debugger command
SlpTypeErr	=	-5	#invalid queue element
unimpErr	=	-4	#unimplemented core routine
corErr	=	-3	#core routine number out of range
dsNoExtsDisassembler	=	-2	#not a SysErr, just a placeholder
qErr	=	-1	#queue element not found during deletion
tsmComponentNoErr	=	0	#component result = no error
EPERM	=	1	#Operation not permitted
ENOENT	=	2	#No such file or directory
ESRCH	=	3	#No such process
EINTR	=	4	#Interrupted system call
EIO	=	5	#Input/output error
ENXIO	=	6	#Device not configured
E2BIG	=	7	#Argument list too long
ENOEXEC	=	8	#Exec format error
EBADF	=	9	#Bad file descriptor
ECHILD	=	10	#No child processes
EDEADLK	=	11	#Resource deadlock avoided
ENOMEM	=	12	#Cannot allocate memory
EACCES	=	13	#Permission denied
EFAULT	=	14	#Bad address
ENOTBLK	=	15	#Block device required
EBUSY	=	16	#Device busy
EEXIST	=	17	#File exists
EXDEV	=	18	#Cross-device link
ENODEV	=	19	#Operation not supported by device
ENOTDIR	=	20	#Not a directory
EISDIR	=	21	#Is a directory
EINVAL	=	22	#Invalid argument
ENFILE	=	23	#Too many open files in system
EMFILE	=	24	#Too many open files
ENOTTY	=	25	#Inappropriate ioctl for device
ETXTBSY	=	26	#Text file busy
EFBIG	=	27	#File too large
ENOSPC	=	28	#No space left on device
ESPIPE	=	29	#Illegal seek
EROFS	=	30	#Read-only file system
EMLINK	=	31	#Too many links
EPIPE	=	32	#Broken pipe
EDOM	=	33	#Numerical argument out of domain
ERANGE	=	34	#Result too large
EAGAIN	=	35	#Resource temporarily unavailable
EINPROGRESS	=	36	#Operation now in progress
EALREADY	=	37	#Operation already in progress
ENOTSOCK	=	38	#Socket operation on non-socket
EDESTADDRREQ	=	39	#Destination address required
EMSGSIZE	=	40	#Message too long
EPROTOTYPE	=	41	#Protocol wrong type for socket
ENOPROTOOPT	=	42	#Protocol not available
EPROTONOSUPPORT	=	43	#Protocol not supported
ESOCKTNOSUPPORT	=	44	#Socket type not supported
EOPNOTSUPP	=	45	#Operation not supported on socket
EPFNOSUPPORT	=	46	#Protocol family not supported
EAFNOSUPPORT	=	47	#Address family not supported by protocol family
EADDRINUSE	=	48	#Address already in use
EADDRNOTAVAIL	=	49	#Can't assign requested address
ENETDOWN	=	50	#Network is down
ENETUNREACH	=	51	#Network is unreachable
ENETRESET	=	52	#Network dropped connection on reset
ECONNABORTED	=	53	#Software caused connection abort
ECONNRESET	=	54	#Connection reset by peer
ENOBUFS	=	55	#No buffer space available
EISCONN	=	56	#Socket is already connected
ENOTCONN	=	57	#Socket is not connected
ESHUTDOWN	=	58	#Can't send after socket shutdown
ETOOMANYREFS	=	59	#Too many references: can't splice
ETIMEDOUT	=	60	#Connection timed out
ECONNREFUSED	=	61	#Connection refused
ELOOP	=	62	#Too many levels of symbolic links
ENAMETOOLONG	=	63	#File name too long
EHOSTDOWN	=	64	#Host is down
EHOSTUNREACH	=	65	#No route to host
ENOTEMPTY	=	66	#Directory not empty
EPROCLIM	=	67	#Too many processes
EUSERS	=	68	#Too many users
EDQUOT	=	69	#Disc quota exceeded
ESTALE	=	70	#Stale NFS file handle
EREMOTE	=	71	#Too many levels of remote in path
EBADRPC	=	72	#RPC struct is bad
ERPCMISMATCH	=	73	#RPC version wrong
EPROGUNAVAIL	=	74	#RPC prog. not avail
EPROGMISMATCH	=	75	#Program version wrong
EPROCUNAVAIL	=	76	#Bad procedure for program
ENOLCK	=	77	#No locks available
ENOSYS	=	78	#Function not implemented
EFTYPE	=	79	#Inappropriate file type or format
EINPROGRESS	=	136	#Operation now in progress
EALREADY	=	137	#Operation already in progress
ENOTSOCK	=	138	#Socket operation on non-socket
EDESTADDRREQ	=	139	#Destination address required
EMSGSIZE	=	140	#Message too long
