#! /bin/sh
case `uname -sr` in
'SunOS 4.'*)	;;
*)	echo Probably not on a SunOS 4 system 1>&2
	exit 1;;
esac
set -v
h2py </usr/include/sys/fcntlcom.h >FCNTL.py
echo "O_ACCMODE = (O_RDONLY|O_WRONLY|O_RDWR)" >>FCNTL.py
h2py /usr/include/sys/socket.h
h2py /usr/include/sys/wait.h
h2py -i '(u_long)' /usr/include/netinet/in.h
