# Generated from 'Macintosh HD:SWDev:Codewarrior Pro 5:Metrowerks CodeWarrior:MacOS Support:Universal:Interfaces:CIncludes:Menus.h'

def FOUR_CHAR_CODE(x): return x
gestaltMenuMgrAttr = FOUR_CHAR_CODE('menu')
gestaltMenuMgrPresent = 1
menuPropertyInvalid = -5603
menuPropertyNotFoundErr = -5604
noMark = 0
kMenuDrawMsg = 0
kMenuChooseMsg = 1
kMenuSizeMsg = 2
kMenuDrawItemMsg = 4
kMenuCalcItemMsg = 5
kMenuThemeSavvyMsg = 7
mDrawMsg = 0
mChooseMsg = 1
mSizeMsg = 2
mDrawItemMsg = 4
mCalcItemMsg = 5
kThemeSavvyMenuResponse = 0x7473
textMenuProc = 0
hMenuCmd = 27
hierMenu = -1
mPopUpMsg = 3
mctAllItems = -98
mctLastIDIndic = -99
kMenuStdMenuProc = 63
kMenuStdMenuBarProc = 63
kMenuNoModifiers = 0
kMenuShiftModifier = (1 << 0)
kMenuOptionModifier = (1 << 1)
kMenuControlModifier = (1 << 2)
kMenuNoCommandModifier = (1 << 3)
kMenuNoIcon = 0
kMenuIconType = 1
kMenuShrinkIconType = 2
kMenuSmallIconType = 3
kMenuColorIconType = 4
kMenuIconSuiteType = 5
kMenuIconRefType = 6
gestaltContextualMenuAttr = FOUR_CHAR_CODE('cmnu')
gestaltContextualMenuUnusedBit = 0
gestaltContextualMenuTrapAvailable = 1
kCMHelpItemNoHelp = 0
kCMHelpItemAppleGuide = 1
kCMHelpItemOtherHelp = 2
kCMNothingSelected = 0
kCMMenuItemSelected = 1
kCMShowHelpSelected = 3
