# Generated from ':::::Waste 1.2 Distribution:WASTE C/C++ Headers:WASTE.h'

weCantUndoErr = -10015
weEmptySelectionErr = -10013
weNotHandledErr = -1708
weUnknownObjectTypeErr = -9478
weObjectNotFoundErr = -9477
weReadOnlyErr = -9476
weUndefinedSelectorErr = -50
weFlushLeft = -2
weFlushRight = -1
weFlushDefault = 0
weCenter = 1
weJustify = 2
weDoFont = 0x0001
weDoFace = 0x0002
weDoSize = 0x0004
weDoColor = 0x0008
weDoAddSize = 0x0010
weDoToggleFace = 0x0020
weDoReplaceFace = 0x0040
weDoPreserveScript = 0x0080
weDoExtractSubscript = 0x0100
weDoFaceMask = 0x0200
kLeadingEdge = -1
kTrailingEdge = 0
kObjectEdge = 2
weFAutoScroll = 0
weFOutlineHilite = 2
weFReadOnly = 5
weFUndo = 6
weFIntCutAndPaste = 7
weFDragAndDrop = 8
weFInhibitRecal = 9
weFUseTempMem = 10
weFDrawOffscreen = 11
weFInhibitRedraw = 12
weFMonoStyled = 13
weFInhibitColor = 31
weDoAutoScroll = 1L << weFAutoScroll
weDoOutlineHilite = 1L << weFOutlineHilite
weDoReadOnly = 1L << weFReadOnly
weDoUndo = 1L << weFUndo
weDoIntCutAndPaste = 1L << weFIntCutAndPaste
weDoDragAndDrop = 1L << weFDragAndDrop
weDoInhibitRecal = 1L << weFInhibitRecal
weDoUseTempMem = 1L << weFUseTempMem
weDoDrawOffscreen = 1L << weFDrawOffscreen
weDoInhibitRedraw = 1L << weFInhibitRedraw
weDoMonoStyled = 1L << weFMonoStyled
weDoInhibitColor = 1L << weFInhibitColor
weBitToggle = -2
weCharByteHook = 'cbyt'
weCharToPixelHook = 'c2p '
weCharTypeHook = 'ctyp'
weClickLoop = 'clik'
weCurrentDrag = 'drag'
weDrawTextHook = 'draw'
weHiliteDropAreaHook = 'hidr'
weLineBreakHook = 'lbrk'
wePixelToCharHook = 'p2c '
wePort = 'port'
weRefCon = 'refc'
weScrollProc = 'scrl'
weText = 'text'
weTranslateDragHook = 'xdrg'
weTSMDocumentID = 'tsmd'
weTSMPreUpdate = 'pre '
weTSMPostUpdate = 'post'
weURLHint = 'urlh'
weWordBreakHook = 'wbrk'
weNewHandler = 'new '
weDisposeHandler = 'free'
weDrawHandler = 'draw'
weClickHandler = 'clik'
weStreamHandler = 'strm'
weAKNone = 0
weAKUnspecified = 1
weAKTyping = 2
weAKCut = 3
weAKPaste = 4
weAKClear = 5
weAKDrag = 6
weAKSetStyle = 7
weToScrap = 0
weToDrag = 1
weToSoup = 2
