#! /bin/sh
set -v
python ../../Tools/scripts/h2py.py /usr/include/fcntl.h
python ../../Tools/scripts/h2py.py /usr/include/sys/socket.h
python ../../Tools/scripts/h2py.py -i '(u_long)' /usr/include/netinet/in.h
python ../../Tools/scripts/h2py.py /usr/include/termios.h
