# Generated from 'Sap:CodeWarrior6:Metrowerks C/C++:Headers:Universal Headers 2.0.1f:Controls.h'

pushButProc = 0
checkBoxProc = 1
radioButProc = 2
scrollBarProc = 16
popupMenuProc = 1008
kControlUsesOwningWindowsFontVariant = 1 << 3
useWFont = 8
kControlNoPart = 0
kControlLabelPart = 1
kControlMenuPart = 2
kControlTrianglePart = 4
kControlButtonPart = 10
kControlCheckBoxPart = 11
kControlRadioButtonPart = 11
kControlUpButtonPart = 20
kControlDownButtonPart = 21
kControlPageUpPart = 22
kControlPageDownPart = 23
kControlIndicatorPart = 129
kControlDisabledPart = 254
kControlInactivePart = 255
inLabel = 1
inMenu = 2
inTriangle = 4
inButton = 10
inCheckBox = 11
inUpButton = 20
inDownButton = 21
inPageUp = 22
inPageDown = 23
inThumb = 129
kControlCheckboxUncheckedValue = 0
kControlCheckboxCheckedValue = 1
kControlCheckboxMixedValue = 2
kControlRadioButtonUncheckedValue = 0
kControlRadioButtonCheckedValue = 1
kControlRadioButtonMixedValue = 2
popupFixedWidth = 1 << 0
popupVariableWidth = 1 << 1
popupUseAddResMenu = 1 << 2
popupUseWFont = 1 << 3
popupTitleBold = 1 << 8
popupTitleItalic = 1 << 9
popupTitleUnderline = 1 << 10
popupTitleOutline = 1 << 11
popupTitleShadow = 1 << 12
popupTitleCondense = 1 << 13
popupTitleExtend = 1 << 14
popupTitleNoStyle = 1 << 15
popupTitleLeftJust = 0x00000000
popupTitleCenterJust = 0x00000001
popupTitleRightJust = 0x000000FF
hAxisOnly = 1
vAxisOnly = 2
cFrameColor = 0
cBodyColor = 1
cTextColor = 2
cThumbColor = 3
drawCntl = 0
testCntl = 1
calcCRgns = 2
initCntl = 3
dispCntl = 4
posCntl = 5
thumbCntl = 6
dragCntl = 7
autoTrack = 8
calcCntlRgn = 10
calcThumbRgn = 11
drawThumbOutline = 12
kDrawControlEntireControl = 0
kDrawControlIndicatorOnly = 129
kDragControlEntireControl = 0
kNoHiliteControlPart = 0
kInLabelControlPart = 1
kInMenuControlPart = 2
kInTriangleControlPart = 4
kInButtonControlPart = 10
kInCheckBoxControlPart = 11
kInUpButtonControlPart = 20
kInDownButtonControlPart = 21
kInPageUpControlPart = 22
kInPageDownControlPart = 23
kInIndicatorControlPart = 129
kReservedControlPart = 254
kControlInactiveControlPart = 255
