/* Do not renumber the file; these numbers are part of the stable ABI. */
#if defined(Py_LIMITED_API)
#undef Py_type_name 1 
#undef Py_type_basicsize 2 
#undef Py_type_itemsize 3 
#undef Py_type_dealloc 4 
#undef Py_type_vectorcall_offset 5
#undef Py_type_getattr 6 
#undef Py_type_setattr 7 
#undef Py_type_repr 8
#undef Py_type_hash 9
#undef Py_type_call 10
#undef Py_type_str 11
#undef Py_type_getattro 12
#undef Py_type_setattro 13
#undef Py_type_flags 14
#undef Py_type_doc 15
#undef Py_type_traverse 16
#undef Py_type_clear 17
#undef Py_type_richcompare 18
#undef Py_type_weaklistoffset 19
#undef Py_type_iter 20
#undef Py_type_iternext 21
#undef Py_type_methods 22
#undef Py_type_members 23
#undef Py_type_getset 24
#undef Py_type_base 25
#undef Py_type_dict 26
#undef Py_type_descr_get 27
#undef Py_type_descr_set 28
#undef Py_type_dictoffset 29
#undef Py_type_init 30
#undef Py_type_alloc 31
#undef Py_type_new 32
#undef Py_type_free 33
#undef Py_type_is_gc 34
#undef Py_type_bases 35
#undef Py_type_mro 36
#undef Py_type_cache 37
#undef Py_type_subclasses 38
#undef Py_type_weaklist 39
#undef Py_type_del 40
#undef Py_type_finalize 41
#else
#define Py_type_name 1
#define Py_type_basicsize 2
#define Py_type_itemsize 3
#define Py_type_dealloc 4
#define Py_type_vectorcall_offset 5
#define Py_type_getattr 6
#define Py_type_setattr 7
#define Py_type_repr 8
#define Py_type_hash 9
#define Py_type_call 10
#define Py_type_str 11
#define Py_type_getattro 12
#define Py_type_setattro 13
#define Py_type_flags 14
#define Py_type_doc 15
#define Py_type_traverse 16
#define Py_type_clear 17
#define Py_type_richcompare 18
#define Py_type_weaklistoffset 19
#define Py_type_iter 20
#define Py_type_iternext 21
#define Py_type_methods 22
#define Py_type_members 23
#define Py_type_getset 24
#define Py_type_base 25
#define Py_type_dict 26
#define Py_type_descr_get 27
#define Py_type_descr_set 28
#define Py_type_dictoffset 29
#define Py_type_init 30
#define Py_type_alloc 31
#define Py_type_new 32
#define Py_type_free 33
#define Py_type_is_gc 34
#define Py_type_bases 35
#define Py_type_mro 36
#define Py_type_cache 37
#define Py_type_subclasses 38
#define Py_type_weaklist 39
#define Py_type_del 40
#define Py_type_finalize 41
#endif
