VID_VP = 0x1000000

# Set vp1 register tokens
VP_GBXORG =       		(VID_VP +0x01)
VP_GBYORG =       		(VID_VP +0x02)
VP_FBXORG =       		(VID_VP +0x03)
VP_FBYORG =       		(VID_VP +0x04)
VP_WIDTH =        		(VID_VP +0x05)
VP_HEIGHT =       		(VID_VP +0x06)
VP_PIXCNT =      		(VID_VP +0x07)
VP_HBLANK =       		(VID_VP +0x08)
VP_VBLANK =      		(VID_VP +0x09)
VP_BRITE =      		(VID_VP +0x0A)
VP_CONT =      			(VID_VP +0x0B)
VP_HUE =      			(VID_VP +0x0C)
VP_SAT =      			(VID_VP +0x0D)
VP_ALPHA =      		(VID_VP +0X0E)
VP_FGMODE =      		(VID_VP +0x0F)
VP_MAPSRC =      		(VID_VP +0x10)
VP_MAPADD =      		(VID_VP +0x11)
VP_MAPRED =      		(VID_VP +0x12)
VP_MAPGREEN =      		(VID_VP +0x13)
VP_MAPBLUE =      		(VID_VP +0x14)
VP_MAPSTROBE =      		(VID_VP +0x15)
VP_DIGVAL =      		(VID_VP +0x16)
VP_STATUS0 =      		(VID_VP +0x17)
VP_STATUS1 =      		(VID_VP +0x18)
VP_CMD =      			(VID_VP +0x19)
