name: Check labels

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

permissions:
  contents: read

jobs:
  label:
    name: DO-NOT-MERGE / unresolved review
    if: github.repository_owner == 'python'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    timeout-minutes: 10

    steps:
      - uses: mheap/github-action-required-labels@0ac283b4e65c1fb28ce6079dea5546ceca98ccbe # v5.5.2
        with:
          mode: exactly
          count: 0
          labels: "DO-NOT-MERGE, awaiting changes, awaiting change review"
