name: Reusable WASI

on:
  workflow_call:

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  build-wasi-reusable:
    name: 'build and test'
    runs-on: ubuntu-26.04
    timeout-minutes: 60
    env:
      WASMTIME_VERSION: 38.0.3
      WASI_SDK_VERSION: 24
      WASI_SDK_PATH: /opt/wasi-sdk
      CROSS_BUILD_WASI: cross-build/wasm32-wasip1
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    # No problem resolver registered as one doesn't currently exist for Clang.
    - name: "Install wasmtime"
      uses: bytecodealliance/actions/wasmtime/setup@9152e710e9f7182e4c29ad218e4f335a7b203613 # v1.1.3
      with:
        version: ${{ env.WASMTIME_VERSION }}
    - name: "Restore WASI SDK"
      id: cache-wasi-sdk
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: ${{ env.WASI_SDK_PATH }}
        key: ${{ runner.os }}-wasi-sdk-${{ env.WASI_SDK_VERSION }}
    - name: "Install WASI SDK"  # Hard-coded to x64.
      if: steps.cache-wasi-sdk.outputs.cache-hit != 'true'
      run: |
        mkdir "${WASI_SDK_PATH}" && \
        curl -s -S --location "https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${WASI_SDK_VERSION}/wasi-sdk-${WASI_SDK_VERSION}.0-x86_64-linux.tar.gz" | \
        tar --strip-components 1 --directory "${WASI_SDK_PATH}" --extract --gunzip
    - name: "Install Python"
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: '3.x'
    - name: "Runner image version"
      run: echo "IMAGE_OS_VERSION=${ImageOS}-${ImageVersion}" >> "$GITHUB_ENV"
    - name: "Configure build Python"
      run: python3 Tools/wasm/wasi configure-build-python -- --config-cache --with-pydebug
    - name: "Make build Python"
      run: python3 Tools/wasm/wasi make-build-python
    - name: "Display build info of the build Python"
      run: python3 Tools/wasm/wasi pythoninfo-build
    - name: "Configure host/WASI Python"
      # `--with-pydebug` inferred from configure-build-python
      run: python3 Tools/wasm/wasi configure-host -- --config-cache
    - name: "Make host/WASI Python"
      run: python3 Tools/wasm/wasi make-host
    - name: "Display build info of the host/WASI Python"
      run: python3 Tools/wasm/wasi pythoninfo-host
    - name: "Test"
      run: make --directory "${CROSS_BUILD_WASI}" test
