name: Mark stale pull requests

on:
  schedule:
  - cron: "0 */6 * * *"

permissions:
  contents: read

jobs:
  stale:
    if: github.repository_owner == 'python'
    runs-on: ubuntu-slim
    permissions:
      actions: write
      pull-requests: write
    timeout-minutes: 10

    steps:
    - name: "Check PRs"
      uses: actions/stale@4391f3da665fdf50b6810c1a66712fb9ba21aa93 # v11.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'This PR is stale because it has been open for 90 days with no activity.'
        stale-pr-label: 'stale'
        days-before-issue-stale: -1
        days-before-pr-stale: 90
        days-before-close: -1
        ascending: true
        operations-per-run: 120
