name: Verify bundled libexpat

on:
  workflow_dispatch:
  push:
    paths:
      - 'Modules/expat/**'
      - '.github/workflows/verify-expat.yml'
      - 'Tools/build/verify_expat.py'
  pull_request:
    paths:
      - 'Modules/expat/**'
      - '.github/workflows/verify-expat.yml'
      - 'Tools/build/verify_expat.py'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3'
      - name: Verify bundled libexpat files
        run: ./Tools/build/verify_expat.py
